### ISSUE TITLE
Chrome opens TDAmerirade page but gives the error when i run auth APIs

### ISSUE THREAD

**Issue by TheMindfulTrader** [alexgolec/tda-api#1]
Hi! I'm a beginner to this and sorry for the basic questions. I'm trying to set up this hard process of Authentication to make the fetch sample price history for AAPL. Crossed few hurdles but keep getting this error when i run the python with API key and token path and redirect URL parameters passed. Chrome opens the URL and shows this error message.

******parameters:****** 
token_path = r"C:/tda-api-master/tda-api-master/Token.txt"
api_key = @@MY API KEY here
redirect_uri = 'https://127.0.0.1' 
**Note: i've tried localhost as well.**

**Error from chrome** 
A third-party application may be attempting to make unauthorized access to your account. For help with your account, contact us. For information on securing your account, visit the TD Ameritrade Security page.  

Howver when i tried to follow below instructions manually as mentioned in their site (https://developer.tdameritrade.com/content/simple-auth-local-apps) it works and gives me tokens after i enter username/pwd and allow permisison to app to access my account.  but i'm not sure how to use that token programmatically in your samples. 
Any thoughts ? thanks a lot again

**Comment by alexgolec** [comment]
So when this happens it's typically because you're not passing *exactly* the URI with which your app is configured. Have you double-checked that you're doing this? 

One common mistake is to configure the app with an `http` address but passing in `https` or vice versa.

**Comment by TheMindfulTrader** [comment]
Thanks for the response. Yes. i have tried all the combinations https/http and localhost vs 127.0.0.1 and all the times i have matched the parameter exactly as set in the TDA App that i've created.

**Comment by TheMindfulTrader** [comment]
When i've tried manually using their site/instruction i get the token. Is there a way i can use this in a text file that i mentioned token_path in your samples . it did not accept the format when i pasted this Token.txt file in the token_path 
 {
  "access_token": @@@@lengthy code i got here
  "refresh_token":@@@@lengthy code i got here
  "scope": "PlaceTrades AccountAccess MoveMoney",
  "expires_in": 1800,
  "refresh_token_expires_in": 7776000,
  "token_type": "Bearer"
}

**Comment by alexgolec** [comment]
I'm experimenting with setting my callback URI and such but I can't seem to reproduce your issue. You've shared privacy-scrubbed code, but I can't use that to help you debug. Can you email me the actual code that isn't working?

**Comment by TheMindfulTrader** [comment]
Thanks! I've emailed you the sample code to your email. Thanks for helping me Appreciate it.

**Comment by alexgolec** [comment]
Offline discussion indicates user error: a character was omitted when copying the API key.

**Comment by TheMindfulTrader** [comment]
Sorry that i've made an error with API_KEY. thanks so much for the awesome support. wow. i could see it's extracting the AAPl sample data. appreciate your help!

**Comment by alexgolec** [comment]
Glad I could help! I'll add a troubleshooting section to the documentation with some tips.
