### ISSUE TITLE
Streaming API does not support async handlers

### ISSUE THREAD

**Issue by berzoidberg** [alexgolec/tda-api#102]
See title

**Comment by jpribyl** [comment]
@alexgolec I'm not sure this code has made it into pip yet 🤔 when I do a pip install it gives me version 0.7.1... which looks like it was published in august. Any chance we could get a new release at some point? 

unrelated, nice birthday in the birthday dividends example 😂 
lastly, THANK YOU SO MUCH for all the work you put into this.
