### ISSUE TITLE
Buy/Sell response JSON can't be parsed

### ISSUE THREAD

**Issue by nicmcd** [alexgolec/tda-api#11]
When performing a buy or sell, the response JSON can't be parsed. 

```
sell_acb = {
  "orderType": "MARKET",
  "session": "NORMAL",
  "duration": "DAY",
  "orderStrategyType": "SINGLE",
  "orderLegCollection": [
    {
      "instruction": "Sell",
      "quantity": 10,
      "instrument": {
        "symbol": "ACB",
        "assetType": "EQUITY"
      }
    }
  ]
}
r = c.place_order(account_number, sell_acb)
assert r.ok, r.raise_for_status()
print(r.json())
```

Yields this error:
```
Traceback (most recent call last):
  File "./test1.py", line 85, in <module>
    print(r.json())
  File "/home/nic/.local/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I have verified on tdameritrade.com that both my buy and sell orders are going through just fine. But the tda-api is returning something that can't be parsed as JSON. Please advise.

**Comment by alexgolec** [comment]
Very interesting. It's possible this is a bug, so thanks for point it out. I wish I could tell you to enable logging and tell me what you see, but logging has been on my `TODO` list for a while now. 

No time like the present, though, I'll write it up and ping you when it's merged.

**Comment by nicmcd** [comment]
Looks like the response status_code is 201. The qualification for r.ok is <= 200. Any idea why TDA is giving back 201?

**Comment by nicmcd** [comment]
Ok, I was wrong. r.ok is true, but the r.status_code is 201. Also, r.content is b''. Does placing an order not return JSON?

**Comment by nicmcd** [comment]
Also, I noticed that a link to my order is in r.header['Location']. I'm surprised that TDA isn't giving back JSON with at least the order number.

**Comment by alexgolec** [comment]
It might seem that way, but that's actually pretty standard HTTP API design. And that example sounds awesome! I'm working on an examples repo that showcases interesting applications, I'd love to include one there once I get it set up.

**Comment by alexgolec** [comment]
FWIW the 201 status means "Created", which seems appropriate for the situation.

**Comment by nicmcd** [comment]
Given this discussion, I think the comments in Utils.find_most_recent_order are wrong. TDA is giving back the order number, but it is just slightly annoying to get at. How about creating a utility function that takes a place_order response and returns the order number? If that sounds good, I'll take a crack at it and give a PR.

**Comment by alexgolec** [comment]
That's a very good catch about the documentation. I wrote that before I realized the located was encoded in the headers. 

As for your second suggestion, there's already a utility for that: 

file:///Users/alexgolec/Documents/tda-api/docs-build/html/util.html#tda.utils.Utils.extract_order_id

**Comment by nicmcd** [comment]
Great! Thanks
