### ISSUE TITLE
A Dockerfile to run simple example

### ISSUE THREAD

**Issue by godrays** [alexgolec/tda-api#113]
I would like to see a Dockerfile in the project where everyone can use to try the library with the right configuration at least once. This would eliminate configuration related issues at the beginning.

One Dockerfile and a bash script file to run an example.

Is this possible?

**Comment by virajbukitagar123** [comment]
According to me the problem might arise in authentication process where the user has to provide credentials manually to get token file.

**Comment by alexgolec** [comment]
You are welcome to [submit a PR](https://tda-api.readthedocs.io/en/stable/contributing.html) or [make an edit to our wiki](https://github.com/alexgolec/tda-api/wiki
).
