### ISSUE TITLE
Closing Websocket safely

### ISSUE THREAD

**Issue by alecspurlock** [alexgolec/tda-api#123]
Hello,

I am struggling to use the logout method within the streaming.py module, is there a recommendation on the proper way to run this script for streaming a few minutes worth of data, then safely exiting the websocket within this code? I can pull the data and process it easily but cannot complete the script due to not safely closing the websocket handshake.

Please advise, I am new to websockets in particular. Anything helps!

-friend

**Comment by alexgolec** [comment]
So unfortunately there is no interface for closing the websocket according to this API, but you can always access `StreamClient._socket` directly to disconnect. 

Also please direct future questions to the discord: discord.gg/nfrd9gh
