### ISSUE TITLE
options_book and timesale_options_subs return nothing

### ISSUE THREAD

**Issue by randomstuff4kosma** [alexgolec/tda-api#131]
**Description of Bug**
I can not stream options_book or timesale_options_subs. I tried researching in various places (docs, Discord) but found nothing that indicates its status from TD Ameritrade. 

**Code to Reproduce**
```python
from tda.auth import easy_client
from tda.client import Client
from tda.streaming import StreamClient
from tda.orders.options import OptionSymbol

import asyncio
import json
import config
import logging

logging.getLogger('').addHandler(logging.StreamHandler())

client = easy_client(
        api_key=config.API_KEY,
        redirect_uri=config.REDIRECT_URI,
        token_path=config.TOKEN_PATH)
stream_client = StreamClient(client, account_id=config.ACCOUNT_ID)

def order_book_handler(msg):
    print(json.dumps(msg, indent=4))

async def read_stream():
    await stream_client.login()
    await stream_client.quality_of_service(StreamClient.QOSLevel.EXPRESS)
    stream_client.add_options_book_handler(order_book_handler)

    await stream_client.options_book_subs(['AAPL'])

    stream_client.add_options_book_handler(order_book_handler)

    while True:
        await stream_client.handle_message()

asyncio.get_event_loop().run_until_complete(read_stream())
```

**Expected Behavior**
Should be able to stream Options Order Book data

**Actual Behavior**
No errors and the terminal is blank. Even with logging and verbose mode for Python, I can not find anything that indicates there was an error. 

**Error/Exception Log, If Applicable**
No errors. I also can not find any exceptions.

**Comment by alexgolec** [comment]
Issues are not an appropriate venue for support. You're welcome to ask your question in our discord: 

https://discord.gg/nfrd9gh
