### ISSUE TITLE
Everytime get "A server error occurred.  Please contact the administrator."

### ISSUE THREAD

**Issue by Shimul22** [alexgolec/tda-api#137]
Hello,  
I write the below code:
``from tda.auth import easy_client``
``from tda.client import Client``
``from tda.streaming import StreamClient``

``client = easy_client(``
      ``api_key=api_key_goes_here,``
      ``redirect_uri="http://127.0.0.1:8858/",``
      ``token_path='/tmp/token.pickle'``
``)``
``stream_client = StreamClient(client, account_id=account_id)``

But when I run this code it returns **A server error occurred.  Please contact the administrator.**
When I debug the code I saw it does not reach this line ``stream_client = StreamClient(client, account_id=account_id)``
What is the actual reason and how can I solve this issue?

**Comment by alexgolec** [comment]
Issues are not an appropriate venue for support. You're welcome to ask your question in our discord:

https://discord.gg/nfrd9gh
