### ISSUE TITLE
FYI See this repo with clean TD Ameritrade API schemas.

### ISSUE THREAD

**Issue by blais** [alexgolec/tda-api#138]
https://github.com/blais/ameritrade-api-schemas

**Comment by alexgolec** [comment]
Noted. These are the same schemas that are present in the online documentation which was used to generate some of this API. Also feel free to add a link to the wiki.

**Comment by blais** [comment]
Yes. But these are automatically scraped and cleaned up from the website (see scripts). The idea is that they can be  used to auto-generate validators or language bindings (instead of doing it by hand, so updating should be easy). I'll be using them in my own API bindings by converting to protocol buffers and writing a converter to/from JSON. Basically the validation / conversion part of the API is separated from the actual mechanics of oauth and request/response and refresh token and all that. It's a layer on top.

Feel free to leverage them and do the same. I'll be maintaining that repository separately from the various language bindings. I'd like to also eventually add in a parseable schema for their streaming API (same idea).

**Comment by blais** [comment]
BTW, what's the best place to discuss API problems with others?
I'm finding myself simply unable to place stop-limit orders.
