### ISSUE TITLE
BaseClient.get_price_history start_date and end_date parameter documentation mix-up

### ISSUE THREAD

**Issue by thomas-schweich** [alexgolec/tda-api#146]
Hello, I was just looking through your repository (looks like you all are doing great work!) as I was attracted to the clever `selenium` usage for authentication. 

I just noticed a small mix-up in the documentation for the get_price_history method--the `start_date` parameter is documented as being the "end date" and the `end_date` parameter is documented as being the "start date". For a moment I thought all the data scraping I've been doing today had gotten to my head, but after cross checking the official docs, it seems this is indeed just a simple mix-up. The relevant line is:

https://github.com/alexgolec/tda-api/blob/64e5c1186df48052f5d4bf1c3dac556696abbd16/tda/client/base.py#L757

Glad to see this repo is so active. I will try to contribute if I come up with anything worth sharing! Cheers.

**Comment by alexgolec** [comment]
Ah, good catch. If you want to create a PR, this seems like a nice and easy way to get your name on the contributors list.
