### ISSUE TITLE
Add UNSUBS and LOGOUT cmd to streaming client

### ISSUE THREAD

**Issue by httran13** [alexgolec/tda-api#152]
**Is your feature request related to a problem? Please describe.**

Currently the streaming client can subscribe to a few services with its fields and we can also use cmd ADD to add more symbols. This allows another parallel process to dynamically add symbols for subscriptions and thus increase resources usage on the app. We need a way to allow another process to manage the sub/unsub of services and logout for graceful shutdown.

**Describe the solution you'd like**
In addition to <service>*_subs functions, we can add *unsubs functions for available services and a logout function to the client.

**Describe alternatives you've considered**
Ive thought about a more generic .send(request) for the client to allow a free .send request to the websocket that can be built by the dev. This will give free reign to the dev to make any request on the websocket channel.

**Additional context**
Adding this these unsubscribe cmds and logout will allow the programmer to manage the streaming client from another process by subscribing/unsubscribing to services as needed without having to reconfigure or take down the application. An example use case is when a parallel process is receiving a trigger from some other services and need to subscribe to a service for a period of time.

**Comment by alexgolec** [comment]
Thanks for the suggestion, but TDA's streaming API does not offer very good support for unsubscribing from streams.

**Comment by alexgolec** [comment]
Looks like I was wrong: 

https://github.com/areed1192/td-ameritrade-python-api/blob/master/td/stream.py

**Comment by httran13** [comment]
https://github.com/alexgolec/tda-api/pull/189

**Comment by httran13** [comment]
Facts :
- ws.recv() throws RuntimeError – if two coroutines call recv() concurrently https://websockets.readthedocs.io/en/stable/api.html#websockets.protocol.WebSocketCommonProtocol.recv

From this fact, we know a few things: We need to timeshare recv(), which we will need to put some locks in place, or we have a single task to handle recv() thus all incoming ws messages.

Our current state in master, correct me if im wrong here, assumes that we subscribe to some service(s) then handle all incoming streaming data in real time and no longer have a need to deal with anymore "responses" type after subscriptions, therefore no longer making anymore request(s) after subscribing. Evidence of this : https://github.com/alexgolec/tda-api/blob/3ed5af205a2bebf5cb3ffd45e4ecd8525f5605fb/tda/streaming.py#L294 where response type raises exception and each subscribe function results in a send then await_response https://github.com/alexgolec/tda-api/blob/3ed5af205a2bebf5cb3ffd45e4ecd8525f5605fb/tda/streaming.py#L288, which means recv() is not being shared but are called from multiple task(s)[ handle_message, and all subscribe functions ]


If we are to pivot from our current state in master to add dynamic ADD/UNSUBS commands to the service(s), we need to use the options above how to deal with recv() ( and these may not cover all of our options, feedback are welcomed )

1. Implement locks on recv(), any sub/add/unsub will need to lock recv(). This imo has consequences and makes streaming not soo real time.
2. Refactor current state to only let 1 task handle recv(). This will change the current state assumption above to setting up the receiver before any ws requests are sent. Also requires refactoring of service_op to only send requests. handle_message will need to handle all 3 known types of messages [ response, data, notify ]
3. Keep current state and add option to enable/disable service_op to await_receive. This has drawback where now the caller will need to know which option to pass to an sub/add/unsub fcn - https://github.com/alexgolec/tda-api/pull/189
4. Keep some global state, if recv() is being handled, avoid calling _await_receive() in service_op

**Comment by r4m0n** [comment]
I'm looking into picking up #106, which should cover the addition of the missing commands and fix the main message processing loop (haven't checked if it's fixed there, but it'll be cleaner to fix there if it isn't).

If that's not doable, I think option 2 above is the cleanest. I'd change service_op to add the request to a list of requests to wait for confirmation, and then handle_message can check them off. But overall I think it's better to proceed with the rewrite of the streaming client that's currently a complete mess and missing half the functionality.

**Comment by httran13** [comment]
@r4m0n thanks! #106 looks like a major change, i haven't checked out the code yet but skimmed it.

I just want to add another observation here from my end:

For streaming acct_activity, over the weekend, my subscrptionKey got expired and I got a message:

```
{"seq": 29, "key": "xxxxxf1ff5f3", "ACCOUNT": "", "MESSAGE_TYPE": "ERROR", "MESSAGE_DATA": "EXPIRED_KEY"}```

with this error, the stream still stays alive and the incoming messages are :
```
{"seq": 0, "key": "xxxx8502442f1ff5f3", "ACCOUNT": "", "MESSAGE_TYPE": "SUBSCRIBED", "MESSAGE_DATA": ""}
```

with no information. 

With this observation, there also needs to perhaps be a subscriptionKey refresh for acct_activity. From my understanding, that can be achieve with this api alone : 

https://github.com/alexgolec/tda-api/blob/114fe192ebc9c292322d3ec308555fff413009fc/tda/client/base.py#L953

then another call to resubsribe to acct_activity.

I will confirm this over the weekend when i have more time to work on this.

**Comment by httran13** [comment]
Want to add an error case here.

If we have several services subscribed and then unsubscribe to all of the services, TD Streaming will close the stream with this error message from ADMIN service

Currently, we do not add handlers to ADMIN service as the only cmd we use from ADMIN service is login, because we dont add any handlers, this useful information is lost.

`2021-09-16 01:15:54 DEBUG client < Frame(fin=True, opcode=<Opcode.TEXT: 1>, data=b'{"notify":[{"service":"ADMIN","timestamp":1631772954749,"content":{"code":30,"msg":"Stop streaming due to empty subscription"}}]}', rsv1=False, rsv2=False, rsv3=False)`

the error information that we get back that is visible is a 1006 connection closed, which is not very useful.

```
2021-09-16 01:15:54 DEBUG client x code = 1006, reason = [no reason]
client ! failing CLOSED WebSocket connection with code 1006
2021-09-16 01:15:54 DEBUG client ! failing CLOSED WebSocket connection with code 1006
```

**Comment by httran13** [comment]
Closing this issue as UNSUBS were added in this PR : https://github.com/alexgolec/tda-api/pull/256

feel free to to open new issues from some of the discovery above
