### ISSUE TITLE
Streaming example throwing async error

### ISSUE THREAD

**Issue by jhaindev** [alexgolec/tda-api#156]
## Please read the [bug submission guidelines](https://tda-api.readthedocs.io/en/latest/help.html) before submitting a bug.

Not following guidelines may result in your bug being ignored and/or closed. 

**Description of Bug**
The streaming example located in the "examples" folder is throwing an error that traces back to asyncio
`coroutine was never awaited` is the relevant text.

**Code to Reproduce**
Copy and paste the streaming example into a python project. Use your own api key, account #, and token path.

IMPORTANT: Remember to anonymize your code. Be sure to replace API keys/Client IDs with placeholders. Also, never, ever share the contents of your token file. 

**Expected Behavior**
Stream works and prints example. 

**Actual Behavior**
Error.

NOTE: This code example still works: https://tda-api.readthedocs.io/en/stable/streaming.html

**Comment by alexgolec** [comment]
Can you please provide a link to the failing code?
