### ISSUE TITLE
How to place orders with a technical chart involved

### ISSUE THREAD

**Issue by manojjenago** [alexgolec/tda-api#157]
Hi, 
This is a beautiful API doc that enables auto trading. I have one query is that we can use some technical analysis and place an order with a signal, Ex - 9 days EMA crosses over 21 Day Ema, then place an order, and when it reverses then exit. 

Thanks,
Manoj

**Comment by alexgolec** [comment]
Issues are not an appropriate venue for support. You're welcome to ask your question in our discord:

https://discord.gg/nfrd9gh
