### ISSUE TITLE
client_from_manual_flow() fails when run on Windows due to readline import

### ISSUE THREAD

**Issue by wchill** [alexgolec/tda-api#158]
## Please read the [bug submission guidelines](https://tda-api.readthedocs.io/en/latest/help.html) before submitting a bug.

Not following guidelines may result in your bug being ignored and/or closed. 

**Description of Bug**
When `tda.auth.client_from_manual_flow()` is called on Windows, the call fails because the `readline` module is not available for Windows, even though it isn't used.

**Code to Reproduce**
```python
self.client = tda.auth.client_from_manual_flow(API_KEY, "https://localhost", TOKEN_FILE)
```

IMPORTANT: Remember to anonymize your code. Be sure to replace API keys/Client IDs with placeholders. Also, never, ever share the contents of your token file. 

**Expected Behavior**
The function call succeeds.

**Actual Behavior**
The following stack trace is raised:
```
Traceback (most recent call last):
  File "C:\Users\wchill\PycharmProjects\bot-test\data_provider\tda.py", line 21, in __init__
    self.client = tda.auth.client_from_manual_flow(API_KEY, "https://localhost", TOKEN_FILE)
  File "C:\Users\wchill\PycharmProjects\bot-test\venv\lib\site-packages\tda\auth.py", line 251, in client_from_manual_flow
    import readline
ModuleNotFoundError: No module named 'readline'
```

**Error/Exception Log, If Applicable**
See here to learn how to turn on debug logging: https://tda-api.readthedocs.io/en/latest/help.html

**Comment by alexgolec** [comment]
Hmmm, looks like we're not testing well enough to capture issues on Windows. I'll set that up and issue a fix once I can replicate.

**Comment by alexgolec** [comment]
This is released as part of v1.1.1, please update using `pip install --upgrade tda-api`

**Comment by wchill** [comment]
Looks like this is still a problem; GitHub Actions is installing from requirements.txt, but setup.py does not read from it so pyreadline isn't installed as part of tda-api installation.

**Comment by alexgolec** [comment]
🤦

Fixed in this new release

**Comment by alexgolec** [comment]
You can go ahead and try `pip install --upgrade tda-api` again
