### ISSUE TITLE
Only warn user about version >= 3.8.0 when using streaming

### ISSUE THREAD

**Issue by nicmcd** [alexgolec/tda-api#16]
https://github.com/alexgolec/tda-api/blob/d49687cb81111d992f833f54cc585721028574e6/tda/__init__.py#L13

Users who don't want to use streaming should not have to see a warning on the command line. Please change the warning to an exception and put it in the stream API calls.

**Comment by alexgolec** [comment]
I dug into this, and it turns out what's only available from 3.8 onward is `unittest`'s elegant support for testing asynchronous methods. I've removed the import restriction, but I've also committed to using 3.8 for testing. PTAL.

**Comment by nicmcd** [comment]
That sounds good to me.
