### ISSUE TITLE
Can't get 5 day history data

### ISSUE THREAD

**Issue by achillis2** [alexgolec/tda-api#176]
I tried to get 5 day history data by using the code below. But I got the bad request response. I could period type MONTH and period ONE_MONTH to get one month daily data though. But I don't need one month history data. How do I get 5 day or just 1 day history data? Is it a limit from TD or the tda-api?

`get_price_history('SPY',
                period_type=Client.PriceHistory.PeriodType.DAY,
                period=Client.PriceHistory.Period.FIVE_DAYS,
                frequency_type=Client.PriceHistory.FrequencyType.DAILY,
                frequency=Client.PriceHistory.Frequency.DAILY
                )`

**Comment by JulianOrteil** [comment]
This is an issue with the way the official api works.

If you check the [official documentation](https://developer.tdameritrade.com/price-history/apis/get/marketdata/%7Bsymbol%7D/pricehistory), you'll see a very confusing configuration table (if you will) to what combinations work together.

I'll do my best to explain why your combination isn't working.

First, you set your `period_type` to `day`. The only valid `frequency_type` that can be used with a `day` `period_type` is `minute`. From there, you can choose a `frequency` of every `1`, `5`, `10`, `15` or `30` minutes.

To get your request working properly, here is an example that will pull the past couple of days:
```
response = client.get_price_history(
    'AAPL',
    period=Client.PriceHistory.Period.ONE_MONTH,
    period_type=Client.PriceHistory.PeriodType.MONTH,
    frequency=Client.PriceHistory.Frequency.DAILY,
    frequency_type=Client.PriceHistory.FrequencyType.DAILY,
    end_datetime=datetime.datetime.now(),
    start_datetime=datetime.datetime.now() - datetime.timedelta(days=5)
)
```

You have to specify a `month` `period` and `period_type`, then set both `frequency` and `frequency_type` to `daily`. Afterwards, you must now specify the `start_datetime` and `end_datetime`.
As you might have noticed, this doesn't return 5 days (I'm posting this on a Friday), so you might have to try some different logic to pull the latest 5 days. Try this on a Saturday and see if it will pull the last week, for example.

**Comment by achillis2** [comment]
Thanks for the explanation. Now it makes much more sense.
