### ISSUE TITLE
Support custom timeout management 

### ISSUE THREAD

**Issue by alexgolec** [alexgolec/tda-api#179]
**Is your feature request related to a problem? Please describe.**
HTTPX defaults to 5s timeouts, and some users require longer and/or no timeouts. 

**Describe the solution you'd like**
Start using a client object and expose it to the user so they can set their HTTPX settings. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by codyfletcher** [comment]
Hey @alexgolec, great work on tda-api. Thank you! ⭐️

Quick question, are you open to splitting this into 2 separate issues:

1. Explicitly set a longer default timeout for tda-api, say 15-30s? The thought being that—while 5s is a sane default for HTTPX and most projects—TDA can't seem to serve up historical transactions and/or orders within 5 seconds even if the queried date range is narrow (e.g. 2020-06-01 to 2020-06-02). 

2. Keep this current issue as-is as a follow up issue. It's a better solution but a more time-intensive one.

**Comment by codyfletcher** [comment]
Found this on [discord](https://discord.com/channels/720378361880248621/720384659732693093/934918230546477117). Posting here in case it's of value to others. 

```python
import httpx

fine_grained_timeout = httpx.Timeout(5.0, connect=1.0)
tda_client.session.timeout = fine_grained_timeout
```

**Comment by alexgolec** [comment]
That's good feedback. I've put together a PR that will address both points.

**Comment by codyfletcher** [comment]
Thanks @alexgolec, you're CRUSHING it!
