### ISSUE TITLE
Start a contrib module

### ISSUE THREAD

**Issue by alexgolec** [alexgolec/tda-api#181]
**Is your feature request related to a problem? Please describe.**
The community has a lot of ideas for functionality they want to see outside the main library, for example closing all open positions automatically.

**Comment by manojjenago** [comment]
Hi Alex , 

Thanks for the details that makes so much easier to interact with TD Ameritade through your API or wrapper. 
I am very new to this and not sure if my question is very silly one. please pardon me in case if it is very basic. 
I was able to do placing of orders through your example. How ever I was wondering about below, 

from tda.orders.common import OrderType
from tda.orders.generic import OrderBuilder

one_triggers_other(
    equity_buy_limit('GOOG', 1, 1310),
    one_cancels_other(
        equity_sell_limit('GOOG', 1, 1400),
        equity_sell_limit('GOOG', 1, 1240)
            .set_order_type(OrderType.STOP_LIMIT)
            .clear_price()
            .set_stop_price(1250)
    )

So my question is how we can use the above to place the order in TDA. 
Like placing the orders we use template (place_order) using Account id , but how we can use in the above template ?? 

Thanks ,
MKJ

**Comment by JulianOrteil** [comment]
> Hi Alex ,
> 
> Thanks for the details that makes so much easier to interact with TD Ameritade through your API or wrapper.
> I am very new to this and not sure if my question is very silly one. please pardon me in case if it is very basic.
> I was able to do placing of orders through your example. How ever I was wondering about below,
> 
> from tda.orders.common import OrderType
> from tda.orders.generic import OrderBuilder
> 
> one_triggers_other(
> equity_buy_limit('GOOG', 1, 1310),
> one_cancels_other(
> equity_sell_limit('GOOG', 1, 1400),
> equity_sell_limit('GOOG', 1, 1240)
> .set_order_type(OrderType.STOP_LIMIT)
> .clear_price()
> .set_stop_price(1250)
> )
> 
> So my question is how we can use the above to place the order in TDA.
> Like placing the orders we use template (place_order) using Account id , but how we can use in the above template ??
> 
> Thanks ,
> MKJ

This is not the place to ask this question, it would be better asked on the [Discord](https://discord.gg/nfrd9gh).

**Comment by manojjenago** [comment]
Thanks for your note , I will ask there..
