### ISSUE TITLE
Is it possible to place one equity order having two legs (one buy order, one sell order)?

### ISSUE THREAD

**Issue by david2chen** [alexgolec/tda-api#183]
**Is your feature request related to a problem? Please describe.**

I am developing pair trading strategy using tda-api.  In pair trading, we usually submit a buy order and simultaneously submit a sell order.  Right now, I use equity_sell_market and equity_buy_market to place two orders.  Is it possible to combine them into one order to ensure that either both are executed successfully or both fail.  I try to avoid the situation that only one leg is executed.

**Describe the solution you'd like**

**Describe alternatives you've considered**

Currently I use equity_sell_market and equity_buy_market. 

**Additional context**

I can be reached at 925-605-9905 or DavidChen2019@yahoo.com.
Your help is very much appreciated.

David

**Comment by alexgolec** [comment]
Issues are not an appropriate venue for support. You're welcome to ask your question in our discord:

https://discord.gg/nfrd9gh
