### ISSUE TITLE
Succeeding in getting access token, error message when submitting it for URL response, can't get accountID

### ISSUE THREAD

**Issue by cstampar** [alexgolec/tda-api#187]
**Description of Bug**
For a few weeks i have had some operational working code to manually authenticate my account from google colab and was successfully accessing my data. Today i started getting a weird error. I am able to get an access token and save it to file, read it in, then try to add token to "headers" and format a url with endpoint/headers to submit and getting this response:

"{'error': 'The access token being passed has expired or is invalid.'}"

I have confirmed that each time i go through the url redirect auth process it is indeed giving me a brand new token, that is then immediately being rejected by TDA. I have printed each token out separately to confirm TDA is generating a new token each time, so that isn't the problem. I have never had a freshly generated token rejected like this. 

**Code to Reproduce**

api_key = 'XYZ....'
redirect_url = 'https://127.0.0.1'
token_path = 'my token path'
client = auth.client_from_manual_flow(api_key=api_key, redirect_url=redirect_url, token_path=token_path)
existing_token_path = 'my token path'
auth.client_from_token_file(token_path=existing_token_path, api_key=api_key)

#get access token
with open('my path', 'rb') as file:
  content = file.read()

tokobject = content.decode('utf-8')
strings = tokobject.split()
access_token = strings[1]

characters_to_remove = '",<'
for character in characters_to_remove:
    access_token = access_token.replace(character,'')

#pass access_token to get accounts info
endpoint = r'https://api.tdameritrade.com/v1/accounts'
headers = {'Authorization': "Bearer {}".format(access_token)}
content = r.get(url=endpoint,headers=headers)
data = content.json()
account_id = data[0]['securitiesAccount']['accountId']

responds with = "{'error': 'The access token being passed has expired or is invalid.'}"

**Expected Behavior**

should authenticate and return account data

**Actual Behavior**

{'error': 'The access token being passed has expired or is invalid.'}

**Error/Exception Log, If Applicable**
{'error': 'The access token being passed has expired or is invalid.'}

Thanks so much!

**Comment by alexgolec** [comment]
Very interesting. What versions are you using? This could be a potential bug, but it could also be user error.

**Comment by alexgolec** [comment]
Wait a minute, you're not using the client at all. This looks like a basic misunderstanding of how to use the library. Please read through the [documentation](https://tda-api.readthedocs.io/en/latest/) to learn more and/or [join the discord](https://discord.gg/nfrd9gh) to ask the community for help.

**Comment by cstampar** [comment]
Writing the code this way was the only way i was able to get it to function properly on Google Colab :) I'm using as much of the library as I can like "auth.client_from_token_file" but then had to customize a few things to get it workings, I had it totally functional for weeks so I don't think its a mistake I made.
