### ISSUE TITLE
Can we trade futures using their streaming api or their rest api?

### ISSUE THREAD

**Issue by odssh** [alexgolec/tda-api#188]
**Is your feature request related to a problem? Please describe.**
I am trying to place future orders using their streaming or rest API but there doesn't seem to be any way to do that and unable to find any documentation either. If possible can you suggest to me how can I place "futures" orders?

**Describe the solution you'd like**
Any kind of documentation for futures orders.

**Describe alternatives you've considered**
Futures order using TD Ameritrade API

**Additional context**
I tried to contact their support team but they never replied

**Comment by alexgolec** [comment]
Issues are not an appropriate venue for support. Please visit out discord to ask the community for help: 

https://discord.gg/nfrd9gh
