### ISSUE TITLE
HTTPX Response Property Names Are Confusing

### ISSUE THREAD

**Issue by BSalita** [alexgolec/tda-api#197]
Just some feedback from an experienced programmer using tda-api for the first time. I'm not a Python expert but the naming conventions for HTTPX properties don't seem standard and are confusing, at least to me and perhaps others. This is a useability issue, a documentation issue, and perhaps a legacy issue.

1) Property .json() is a method that returns a Python object, not a JSON string. Is that a standard name? Seems like to_object() or such would be more clear.

2) Property .text is a property that returns the string representation of the JSON. Seems like to_string() or such would be more clear.

**Comment by alexgolec** [comment]
Thanks for the feedback. I can't say I disagree with you, but what exactly would you propose to address this?
