### ISSUE TITLE
Tda-api client wrapper connection

### ISSUE THREAD

**Issue by cedhigel** [alexgolec/tda-api#2]
Hi,

first thank you for your help and time.

So I copied all the functions and library code from the four scripts auth, client, order and utils from here :
https://github.com/alexgolec/tda-api/tree/master/tda  

then i used the client wrapper code from here:  
https://github.com/alexgolec/tda-api/blob/master/docs/client.rst

using my api key, my localhost and defined:  
token_path='tok'    (in order to get a new file created that will be updated later on with the token if i understood well)

so when executing :

    c = easy_client(
            api_key='APIKEY',
            redirect_uri='https://localhost',
            token_path='/tmp/token.pickle')

    resp = c.get_price_history('AAPL',
            period_type=Client.PriceHistory.PeriodType.YEAR,
            period=Client.PriceHistory.Period.TWENTY_YEARS,
            frequency_type=Client.PriceHistory.FrequencyType.DAILY,
            frequency=Client.PriceHistory.Frequency.DAILY)
    assert resp.ok
    history = resp.json()

I receive

    ---------------------------------------------------------------------------
    FileNotFoundError                         Traceback (most recent call last)
    <ipython-input-6-8a4ca7b0fff6> in <module>
          2         api_key='redacted',
          3         redirect_uri='http://127.0.0.1',
    ----> 4         token_path='tok')
          5 
          6 resp = c.get_price_history('AAPL',
    <ipython-input-4-bacd51c4b48c> in easy_client(api_key, redirect_uri, token_path, 
    webdriver_func)
        114 
        115     try:
    --> 116         return client_from_token_file(token_path, api_key)
        117     except FileNotFoundError:
        118         if webdriver_func is not None:

    <ipython-input-4-bacd51c4b48c> in client_from_token_file(token_path, api_key)
         28 
         29     # Load old token from secrets directory
    ---> 30     with open(token_path, 'rb') as f:
         31         token = pickle.load(f)
         32 

    FileNotFoundError: [Errno 2] No such file or directory: 'tok'

    So I do not know what to do since if i understood well the code should be creating the file

**Comment by alexgolec** [comment]
Is there a reason why you copied the code instead of installing via PyPI? I ask because that's a nonstandard installation method and I can't offer any help there. 

Also note I edited your comment to remove your API key because I don't think you meant to share it. 

Also also, your report is pretty hard to read because I think you messed up some formatting?

**Comment by cedhigel** [comment]
Thanks for hiding the api key.

by installing via PyPl you mean:
    !pip install tda-api

if so once i did it I ran this:
    from tda.auth import easy_client
    from tda.client import Client

    c = easy_client(
            api_key='key',
            redirect_uri='localhost',
            token_path='/tmp/token.pickle')

    resp = c.get_price_history('AAPL',
            period_type=Client.PriceHistory.PeriodType.YEAR,
            period=Client.PriceHistory.Period.TWENTY_YEARS,
            frequency_type=Client.PriceHistory.FrequencyType.DAILY,
            frequency=Client.PriceHistory.Frequency.DAILY)
    assert resp.ok 
    history = resp.json()

i get:

    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-2-e8a5adbed35f> in <module>
          8         token_path='/tmp/token.pickle')
          9 
    ---> 10 resp = c.get_price_history('AAPL',
         11         period_type=Client.PriceHistory.PeriodType.YEAR,
         12         period=Client.PriceHistory.Period.TWENTY_YEARS,

    AttributeError: 'NoneType' object has no attribute 'get_price_history'

but the get_price_history is stored in the client file which is imported above, no?

**Comment by alexgolec** [comment]
I'm sorry, but I've tried and failed to reproduce your issue.

**Comment by cedhigel** [comment]
Ok thanks for your time I ll try to figure that out

**Comment by cedhigel** [comment]
just one last question i run this code on a notebook jupyter can this be the problem?

**Comment by alexgolec** [comment]
It’s certainly possible. If you cannot reproduce this issue outside a notebook then it could be a notebook issue.
