### ISSUE TITLE
`get_orders_by_path` returns empty list

### ISSUE THREAD

**Issue by ivnle** [alexgolec/tda-api#205]
**Description of Bug**
`get_orders_by_path` is returning an empty list `[]` instead of a list of my orders. If I use the tool on [TDA's page](https://developer.tdameritrade.com/account-access/apis/get/accounts/%7BaccountId%7D/orders-0) for this function, it successfully returns my orders. I'm also able to use `get_account` with the `ORDERS` field to return my orders.

**Code to Reproduce**
```
from tda import auth, client
import json
import config

try:
    c = auth.client_from_token_file(config.token_path, config.api_key)
except FileNotFoundError:
    from selenium import webdriver
    with webdriver.Chrome(executable_path='/home/user/chromedriver') as driver:
        c = auth.client_from_login_flow(
            driver, config.api_key, config.redirect_uri, config.token_path)

def getOrders(client):
    r = client.get_orders_by_path(config.account_id)
    return r.json()

r = getPutOrders(client=c)
print(json.dumps(r, indent=4))
```

**Expected Behavior**
Return a list populated with my orders.

**Actual Behavior**
Returns an empty list.

**Error/Exception Log, If Applicable**
N/A

**Comment by ivnle** [comment]
For anyone else with the same issue, a temporary work around is to use `c.get_order("", config.account_id)`. This is equivalent to using the `Get Orders By Path` endpoint.

**Comment by alexgolec** [comment]
Are you still getting this issue? I attempted to replicate and got plenty of orders.
