### ISSUE TITLE
streaming client help

### ISSUE THREAD

**Issue by freephys** [alexgolec/tda-api#209]
Testing the streaming of  receive book snapshots of GOOG  example from https://tda-api.readthedocs.io/en/stable/streaming.html
The APIKEY and token has been generated and tested with c = auth.client_from_token_file(token_path, api_key) to get historical quotes. 
But I do not know why do I receive "WebSocket connection is closed: code = 1000 (OK), no reason" from the streaming client?
For the account_id=1234567890 , should it be replaced with a real td account id with int type, right?

Thanks

**Comment by alexgolec** [comment]
Issues are not an appropriate venue for support. Please visit our discord to ask the community for help:

https://discord.gg/nfrd9gh
