### ISSUE TITLE
KeyError: 50

### ISSUE THREAD

**Issue by ipdinc** [alexgolec/tda-api#21]
Hi Alex,

I'm trying to run the example script you provided at the top of page
https://tda-api.readthedocs.io/en/latest/client.html

I have substituted my full windows path in the _token_path_ parameter of function **easy_client()**.  That path ends with the name of a text file that contains only the access token that was returned to me by TD Ameritrade when I authorized my developer account.

Running the script as described returns the message
**KeyError: 50**

Is this error specific to your tda-api client, or is it being returned by TD Ameritrade?  Would you know how to resolve it?

**Comment by alexgolec** [comment]
Please provide the offending code and the the full output of the error message.

**Comment by ipdinc** [comment]
The code I'm running is:

```
from tda.auth import easy_client
from tda.client import Client

c = easy_client(
        api_key='APIKEY',
        redirect_uri='https://localhost',
        token_path='C:/Anaconda3/envs/tda-api/tmp/token.txt')

resp = c.get_price_history('AAPL',
        period_type=Client.PriceHistory.PeriodType.YEAR,
        period=Client.PriceHistory.Period.TWENTY_YEARS,
        frequency_type=Client.PriceHistory.FrequencyType.DAILY,
        frequency=Client.PriceHistory.Frequency.DAILY)
assert resp.ok
history = resp.json()
```

And the output is:

C:\Anaconda3\envs\tda-api\python.exe C:/Anaconda3/envs/tda-api/Scripts/tdi_test.py
Traceback (most recent call last):
  File "C:/Anaconda3/envs/tda-api/Scripts/tdi_test.py", line 8, in <module>
    token_path='C:/Anaconda3/envs/tda-api/tmp/token.txt')
  File "C:\Anaconda3\envs\tda-api\lib\site-packages\tda\auth.py", line 125, in easy_client
    return client_from_token_file(token_path, api_key)
  File "C:\Anaconda3\envs\tda-api\lib\site-packages\tda\auth.py", line 38, in client_from_token_file
    token = pickle.load(f)
KeyError: 50

Process finished with exit code 1

**Comment by alexgolec** [comment]
Just to be clear about `a text file that contains only the access token that was returned to me by TD Ameritrade when I authorized my developer account`: Is this a text file that was generated by call to `easy_client` or a file that you populated yourself?

**Comment by ipdinc** [comment]
I populated it myself.

**Comment by alexgolec** [comment]
Ah, there's your problem. This is a common error. I've added a section to the documentation that explains this: 

https://tda-api.readthedocs.io/en/latest/auth.html#token-parsing-failures

**Comment by ipdinc** [comment]
Thank you so much for your help with this, and for all the work you have put into developing this TDA client!
