### ISSUE TITLE
websockets 9.0.0+ missing client library

### ISSUE THREAD

**Issue by alexgolec** [alexgolec/tda-api#215]
**Description of Bug**
People are starting to report `AttributeError: module 'websockets' has no attribute 'client'` when using websocket. 

I've reproduced this by verifying that websockets 9.0.0+ is missing the client submodule whereas 8.0.0 has it. The short-term workaround is to require `websockets<=8.0.0`. The longer term fix will be to fix the library itself. 

**Code to Reproduce**
Skipped

**Actual Behavior**
`AttributeError: module 'websockets' has no attribute 'client'`

**Comment by r4m0n** [comment]
Not a bug, that's a change on the websockets library. https://websockets.readthedocs.io/en/stable/changelog.html#id4
