### ISSUE TITLE
UnsupportedTokenTypeError: Unsupported token_type: 'access_token'`

### ISSUE THREAD

**Issue by richdevboston** [alexgolec/tda-api#217]
The client gets created, but the access token is the wrong type.  I am not sure what is causing this.  

Here's the code that I am executing: 

`try:
    c = auth.client_from_token_file(config.token_path, config.api_key)
except FileNotFoundError:
    from selenium import webdriver
    with webdriver.Chrome(executable_path='C:\\ProgramData\\PythonCode\\tda\\chromedriver\\chromedriver') as driver:
        c = auth.client_from_login_flow(
            driver, config.api_key, config.redirect_uri, config.token_path)`

And here's the error message that I am getting.   

`---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
C:\ProgramData\Anaconda3\envs\topss2\lib\site-packages\authlib\integrations\httpx_client\oauth2_client.py in auth_flow(self, request)
     30         try:
---> 31             url, headers, body = self.prepare(
     32                 str(request.url), request.headers, request.content)

C:\ProgramData\Anaconda3\envs\topss2\lib\site-packages\authlib\oauth2\auth.py in prepare(self, uri, headers, body)
     97         uri, headers, body = sign(
---> 98             self.token['access_token'],
     99             uri, headers, body,

KeyError: 'access_token'

During handling of the above exception, another exception occurred:

UnsupportedTokenTypeError                 Traceback (most recent call last)
<ipython-input-20-2a05ad8a927e> in <module>
      1 # Get 20-year price history for MSFT
----> 2 r = c.get_price_history('MSFT',
      3         period_type=client.Client.PriceHistory.PeriodType.YEAR,
      4         period=client.Client.PriceHistory.Period.TWENTY_YEARS,
      5         frequency_type=client.Client.PriceHistory.FrequencyType.DAILY,

C:\ProgramData\Anaconda3\envs\topss2\lib\site-packages\tda\client\base.py in get_price_history(self, symbol, period_type, period, frequency_type, frequency, start_datetime, end_datetime, need_extended_hours_data)
    810 
    811         path = '/v1/marketdata/{}/pricehistory'.format(symbol)
--> 812         return self._get_request(path, params)
    813 
    814     ##########################################################################

C:\ProgramData\Anaconda3\envs\topss2\lib\site-packages\tda\client\synchronous.py in _get_request(self, path, params)
     13             req_num, dest, json.dumps(params, indent=4)))
     14 
---> 15         resp = self.session.get(dest, params=params)
     16         self._log_response(resp, req_num)
     17         register_redactions_from_response(resp)

C:\ProgramData\Anaconda3\envs\topss2\lib\site-packages\httpx\_client.py in get(self, url, params, headers, cookies, auth, allow_redirects, timeout)
    905         **Parameters**: See `httpx.request`.
    906         """
--> 907         return self.request(
    908             "GET",
    909             url,

C:\ProgramData\Anaconda3\envs\topss2\lib\site-packages\authlib\integrations\httpx_client\oauth2_client.py in request(self, method, url, withhold_token, auth, **kwargs)
    198             auth = self.token_auth
    199 
--> 200         return super(OAuth2Client, self).request(
    201             method, url, auth=auth, **kwargs)
    202 

C:\ProgramData\Anaconda3\envs\topss2\lib\site-packages\httpx\_client.py in request(self, method, url, content, data, files, json, params, headers, cookies, auth, allow_redirects, timeout)
    731             cookies=cookies,
    732         )
--> 733         return self.send(
    734             request, auth=auth, allow_redirects=allow_redirects, timeout=timeout
    735         )

C:\ProgramData\Anaconda3\envs\topss2\lib\site-packages\httpx\_client.py in send(self, request, stream, auth, allow_redirects, timeout)
    765         auth = self._build_request_auth(request, auth)
    766 
--> 767         response = self._send_handling_auth(
    768             request,
    769             auth=auth,

C:\ProgramData\Anaconda3\envs\topss2\lib\site-packages\httpx\_client.py in _send_handling_auth(self, request, auth, timeout, allow_redirects, history)
    797     ) -> Response:
    798         auth_flow = auth.sync_auth_flow(request)
--> 799         request = next(auth_flow)
    800 
    801         for hook in self._event_hooks["request"]:

C:\ProgramData\Anaconda3\envs\topss2\lib\site-packages\httpx\_auth.py in sync_auth_flow(self, request)
     65 
     66         flow = self.auth_flow(request)
---> 67         request = next(flow)
     68 
     69         while True:

C:\ProgramData\Anaconda3\envs\topss2\lib\site-packages\authlib\integrations\httpx_client\oauth2_client.py in auth_flow(self, request)
     34         except KeyError as error:
     35             description = 'Unsupported token_type: {}'.format(str(error))
---> 36             raise UnsupportedTokenTypeError(description=description)
     37 
     38 

UnsupportedTokenTypeError: unsupported_token_type: Unsupported token_type: 'access_token'`

**Comment by alexgolec** [comment]
Ignoring due to poor formatting. Please format issue properly for help.
