### ISSUE TITLE
Cannot create an order with a stop loss

### ISSUE THREAD

**Issue by lmgonca** [alexgolec/tda-api#222]
## Please read the [bug submission guidelines](https://tda-api.readthedocs.io/en/latest/help.html) before submitting a bug.

Not following guidelines may result in your bug being ignored and/or closed. 

**Description of Bug**
Getting a return code 400 when submitting an equitity order with a stop:

**Code to Reproduce**
tda.orders.equities.equity_buy_limit(symbol,size,limit_price).set_session(session).set_duration(duration).set_stop_price(stop_loss_price).set_stop_price_link_basis(tda.orders.common.StopPriceLinkBasis.LAST).build()

If I use the following code (without stop loss), the order is successfully created:
tda.orders.equities.equity_buy_limit(symbol, size, limit_price).set_session(session).set_duration(duration).build()

IMPORTANT: Remember to anonymize your code. Be sure to replace API keys/Client IDs with placeholders. Also, never, ever share the contents of your token file. 

**Expected Behavior**
Expected the order to be created and code 201 returned.

**Actual Behavior**
Get 400 code as return and order is not created.

**Error/Exception Log, If Applicable**
N/A

**Comment by alexgolec** [comment]
This looks like you're somehow misconfiguring the stop. I've got a change in flight to simplify the process of figuring out how to correctly place complex orders. You can follow along on this PR, and note I'll be releasing this change with version `1.3.0` soon: 

https://github.com/alexgolec/tda-api/pull/221

Meanwhile, I'll ask that you take this question to discord: 

https://discord.gg/nfrd9gh
