### ISSUE TITLE
How to create complex orders?

### ISSUE THREAD

**Issue by aliakhter1** [alexgolec/tda-api#23]
How do you create complex/multi-leg orders? 

E.g. OCO (one cancels other), or with multiple option legs. 

And how do you create order types other than limit/market? E.g. stop loss, trailing stop, etc.

There are examples of these on the TD Ameritrade api site, but I can't figure if these are built into the library, or if there is a workaround. If they are not available, is it planned for a future release?

**Comment by eyesuk** [comment]
Check this out https://github.com/areed1192/td-ameritrade-python-api

**Comment by alexgolec** [comment]
Complex orders are on my TODO list, so stay tuned. @aliakhter1 @eyesuk I would actually appreciate some advice and guidance on this topic, if you're willing to spend the time. I'm not particularly experienced with these sorts of complex order types, so I could use some advice. A quick Zoom/Hangouts call or Discord chat would do wonders. 

Feel free to email me at bottomless.septic.tank@gmail.com if you'd be willing to help.

**Comment by nicmcd** [comment]
Just an FYI, I attempted to issue a multi-leg order using tda-api following examples from here: https://developer.tdameritrade.com/content/place-order-samples, and got "unexpected server errors". So I think TDA may have inconsistencies in their API.

**Comment by alexgolec** [comment]
Which example did you find they rejected?

**Comment by nicmcd** [comment]
I just tried it again, and TDA gave me a new error message, one that is far more helpful! Now is says:

`All legs of a complex options order must be for the same underlying equity.`

I thought I could craft a single order that buys/sells many equities. I was wrong and now the error message is more helpful.

**Comment by alexgolec** [comment]
So this makes for a philosophical quandary: on one hand, my goal is to allow the user to do with ``tda-api`` whatever is possible using the bare API. On the other, validation like this is useful because it makes it easier to craft orders successfully. 

I think the way I'll attack this is: I'll create an API wrapper that implements the entirety of the order schema described [here](https://developer.tdameritrade.com/account-access/apis/post/accounts/%7BaccountId%7D/orders-0), but with zero validation. With that as a base, we can then build a library of known-good order types that are stupidproof and implemented using that framework.

**Comment by aliakhter1** [comment]
I would agree that validation should be left to TD Ameritrade, I have received error/mesaages that are not even listed on their site and are a bit inconsistent. 

I would also add the ability to modify specific order details e.g. a multi leg orders for options may need to be modified where only one leg needs to be changed compared to what their api might return for a given strategy.

**Comment by aliakhter1** [comment]
I am just getting started with it, if I come up with any ideas for implementing improvements I will share.

**Comment by nicmcd** [comment]
@alexgolec, given that tda-api returns the raw response, what is the logic behind not having the user of the API give raw order specifications? If the purpose is to early detect malformed order specifications, have you considered just making a check() function instead?

**Comment by alexgolec** [comment]
`place_order` takes a raw JSON-compatible objects, users can build them and send them as they see fit, without regard to correctness. The order spec creators are utilities that simplify the process by providing a "stupidproof" interface for creating well-known orders, but I never claim they're exhaustive.

**Comment by ChocoShell** [comment]
I've been working on an order builder for another tdameritrade project.

Here is my diff to that project adding a lot of order enums.

If you want to look at one file, check this one out: https://github.com/ChocoShell/tdameritrade/blob/3db557ef2c2ff2668ed10637b740d677d3669119/tdameritrade/orders/orders.py

It has the main `Order` dataclass and I'm messing around creating sample functions to create orders.  Right now, I have a very specific `build_buy_market_stock_order`

I want to implement the [place order samples](https://developer.tdameritrade.com/content/place-order-samples) first but people can create their own order functions using all these constants.
