### ISSUE TITLE
the order status from api is wrong

### ISSUE THREAD

**Issue by weiguang-zz** [alexgolec/tda-api#232]
Has anyone encountered this problem？The order status synchronized from the api is different from the order status on thinkorswim. 

for example:
Below is the order status of thinkorswim
![image](https://user-images.githubusercontent.com/17842829/119831183-98089700-bf2f-11eb-8bc4-da75379d0b2c.png)

 the status from the get order api:
![image](https://user-images.githubusercontent.com/17842829/119831262-af478480-bf2f-11eb-8482-4ef0cf180081.png)

It seems that the API has a high latency.

looking forward to you reply, thank you.

**Comment by alexgolec** [comment]
Sorry, I can't interpret your screenshot, what order status is it supposed to have?

**Comment by weiguang-zz** [comment]
@alexgolec The order status should be filled, but the order status obtained using get order api is queued. 
This is not the problem of the SDK, but the problem of tdameritrade. I just want to ask if anyone has encountered this problem, that is, the get_order api is delayed in obtaining the order status.

**Comment by alexgolec** [comment]
What happens if you look at the order status through the tdameritrade.com
UI instead of TOS?

**Comment by alexgolec** [comment]
Sounds like this is not a bug report but rather a request for experiences. This is not an appropriate use of bug reports, however it is very much an appropriate use of our discord server: 

https://discord.gg/nfrd9gh

Please feel free to ask your question there.
