### ISSUE TITLE
Enforce Nums

### ISSUE THREAD

**Issue by mm0** [alexgolec/tda-api#234]
Hello, perhaps I'm missing the point, but it appears that the enum enforcement of the BaseClient methods forces you to provide certain parameter values that are at times optional.  

For example, when calling `Client.get_option_chain`, to retrieve an option chain, the `exp_month` value is an optional server side filter.  However, by default this field is required when `enforce_enums=True`(default).
It appears that the `EnumEnforcer.convert_enum` method should accept a third parameter `Optional=False` in order to allow optional query parameters to be excluded from requests such as these without raising a `type_error`.
  
https://github.com/alexgolec/tda-api/blob/5bb743a7bb55f992f5d2f6ffb1a41ec99247ac50/tda/client/base.py#L649

**Comment by alexgolec** [comment]
I'm confused, how does [this](https://tda-api.readthedocs.io/en/latest/client.html#tda.client.Client.get_option_chain) API require you to specify an `exp_month`? The `convert_enum` function [returns](https://github.com/alexgolec/tda-api/blob/5bb743a7bb55f992f5d2f6ffb1a41ec99247ac50/tda/utils.py#L44) `None` if `None` is passed. Then that value is [ignored](https://github.com/alexgolec/tda-api/blob/master/tda/client/base.py#L682) later on in the function. 

If you have a specific concern, please resubmit following the bug template.
