### ISSUE TITLE
authentication failure

### ISSUE THREAD

**Issue by montyhall** [alexgolec/tda-api#24]
Hey

I've created an app on TD Ameritrade with a callback URL `https://127.0.0.1:8080` (as [suggested](https://developer.tdameritrade.com/content/authentication-faq) on developer pages). I am making sure I am sending the correct API_KEY and redirect_url to the authentication flow

```
with webdriver.Chrome() as driver:
    c = auth.client_from_login_flow(driver, apikey, redirect_uri, token_path)
```

However, I am getting the error page `a third party application` [you document](https://tda-api.readthedocs.io/en/latest/auth.html). 

Logging shows the port on the localhost being sent with the GET is different however

```
2020-06-08 16:48:47,541 DEBUG    GET http://127.0.0.1:57214/session/<SESSION>/url {}
2020-06-08 16:48:47,544 DEBUG    http://127.0.0.1:57214 "GET /session/<SESSION>/url HTTP/1.1" 200 189
2020-06-08 16:48:47,544 DEBUG    Finished Request
```

**Comment by alexgolec** [comment]
So just to be clear, the issue is you're passing `https://127.0.0.1:8080` as your redirect URI and when it redirects you it sends a request to `https://127.0.0.1:57214`? 

Also, it would make it a lot easier to help you debug if you added the broken code.

**Comment by montyhall** [comment]
correct. the code is the above :) just trying to get a token

**Comment by alexgolec** [comment]
I'm going to need to reproduce the bug if I'm going to investigate this as a bug. The code you've added isn't helpful.

**Comment by montyhall** [comment]
there really is no other meaningful code other than what i pasted above. full code

```
import argparse
import logging
from tda import auth
import json
import _jsonnet
from selenium import webdriver

logging.basicConfig(format='%(asctime)s %(levelname)-8s %(message)s',
                    level=logging.DEBUG)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='authenticate and get token from TDA')

    parser.add_argument('--keys',
                        type=str,
                        default='config/apis.jsonnet',
                        help='API keys',
                        required=True)

    args = parser.parse_args()

    for attr, value in sorted(args.__dict__.items()):
        print("\t{}={}".format(attr.upper(), value))

    keys = json.loads(_jsonnet.evaluate_file(args.keys))
    apikey = keys['TD']['key']
    redirect_uri = keys['TD']['redirect_uri']
    token_path = keys['TD']['token_path']

    with webdriver.Chrome() as driver:
        c = auth.client_from_login_flow(driver, apikey, redirect_uri, token_path)
```

**Comment by alexgolec** [comment]
And you've verified that 

1. You've set `https://127.0.0.1:8080` as your callback URI? 
2. You've copy-pasted your callback URI and API key from the TD Ameritrade API list? Not typed, copy-pasted. 
3. The library you're using to read the keys is actually reading the expected callback URI and API key?

**Comment by montyhall** [comment]
what i'm seeing

```
2020-06-08 17:29:58,088 DEBUG    POST http://127.0.0.1:58229/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "platformName": "any", "goog:chromeOptions": {"extensions": [], "args": []}}}, "desiredCapabilities": {"browserName": "chrome", "version": "", "platform": "ANY", "goog:chromeOptions": {"extensions": [], "args": []}}}
2020-06-08 17:29:58,089 DEBUG    Starting new HTTP connection (1): 127.0.0.1:58229
2020-06-08 17:29:58,998 DEBUG    http://127.0.0.1:58229 "POST /session HTTP/1.1" 200 726
2020-06-08 17:29:58,999 DEBUG    Finished Request
2020-06-08 17:29:59,000 DEBUG    Generated new state STATE_DATA.
Opening the login page in a webdriver. Please use this window to log in. Successful login will be detected automatically.
If you encounter any issues, see here for troubleshooting: https://tda-api.readthedocs.io/en/latest/auth.html#troubleshooting
2020-06-08 17:29:59,000 DEBUG    POST http://127.0.0.1:58229/session/SESSION_ID/url {"url": "https://auth.tdameritrade.com/auth?response_type=code&client_id=CLIENT_ID&redirect_uri=https%3A%2F%2F127.0.0.1%3A8080&state=STATE_DATA"}
2020-06-08 17:29:59,542 DEBUG    http://127.0.0.1:58229 "POST /session/SESSION_ID/url HTTP/1.1" 200 14
2020-06-08 17:29:59,543 DEBUG    Finished Request
```
the driver calls GET step above indefinitely

**Comment by montyhall** [comment]
> And you've verified that
> 
> 1. You've set `https://127.0.0.1:8080` as your callback URI?
> 2. You've copy-pasted your callback URI and API key from the TD Ameritrade API list? Not typed, copy-pasted.
> 3. The library you're using to read the keys is actually reading the expected callback URI and API key?

yes to all above.. see the `POST` at `2020-06-08 17:29:59,000`

**Comment by alexgolec** [comment]
I'm confused, where does `http://127.0.0.1:58229` come from?

**Comment by montyhall** [comment]
> I'm confused, where does `http://127.0.0.1:58229` come from?

lol.. i thought you may know

**Comment by alexgolec** [comment]
Huh, that's weird. I'll dig into it.

**Comment by alexgolec** [comment]
So based on your code, my primary suspect is currently the key loading logic you have here. What happens when you input the redirect URI and API key directly instead of loading it dynamically?

**Comment by montyhall** [comment]
same problem

**Comment by montyhall** [comment]
seems to be something with the

```
with webdriver.Chrome() as driver:
        c = auth.client_from_login_flow(driver, apikey, redirect_uri, token_path)
```

If i try to get the token using the `auth.easy_client` it works. Full code

```
import argparse
import logging
from tda import auth
import json
import _jsonnet
from selenium import webdriver
import atexit
import tda

logging.basicConfig(format='%(asctime)s %(levelname)-8s %(message)s',
                    level=logging.DEBUG)

def make_webdriver():
    from selenium import webdriver
    driver = webdriver.Chrome()
    atexit.register(lambda: driver.quit())
    return driver

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='authenticate and get token from TDA')

    parser.add_argument('--keys',
                        type=str,
                        default='config/apis.jsonnet',
                        help='API keys',
                        required=True)

    args = parser.parse_args()

    keys = json.loads(_jsonnet.evaluate_file(args.keys))
    apikey = keys['TD']['key']
    redirect_uri = keys['TD']['redirect_uri']
    token_path = keys['TD']['token_path']

    client = tda.auth.easy_client(
        apikey,
        redirect_uri,
        token_path,
        make_webdriver)
```

**Comment by alexgolec** [comment]
Interesting. I'm using your code and applying my own credentials and I have no issues, again pointing to the problem being on your end. Can you send a screenshot of your application info from the TD Ameritrade API to bottomless.septic.tank@gmail.com? In particular, I'd like to see your Client ID and redirect URI.

**Comment by alexgolec** [comment]
Apologies for the persistence, but 99.9% of the time this particular issue is caused by user error, so I want to rule it out.

**Comment by alexgolec** [comment]
Also I’ve verified that those GET requests are being sent to the chromedriver, so we can ignore them.

**Comment by montyhall** [comment]
can you try one hypothesis? I was trying the API on TD developers page

https://developer.tdameritrade.com/price-history/apis/get/marketdata/%7Bsymbol%7D/pricehistory

I noticed i had to keep authenticating. Trying to see if there is an interference if you authenticate via the website?

Can you see if it works for you?

**Comment by alexgolec** [comment]
But if you authenticate, does the call go through? Having to re-authenticate sounds like some weirdness with cookies, although it's definitely strange that you're seeing bad behavior both through the API and through TDA's web UI.

**Comment by alexgolec** [comment]
Also, on `client_from_login_flow` vs `easy_client` that's *super* weird, because `easy_client` uses `client_from_login_flow` under the hood.

**Comment by alexgolec** [comment]
I'm also happy to take some time to help you over video if you like. Feel free to reach out to me over the email I shared above.

**Comment by alexgolec** [comment]
Discussed this offline, it turns out the `client_from_login_flow` is not adding the `@AMER.OAUTHAP` suffix. I'll fix this soon.
