### ISSUE TITLE
'get_option_chain' method returns OK response, but no data

### ISSUE THREAD

**Issue by chartwizard** [alexgolec/tda-api#242]
**Description of Bug**
'get_option_chain' method returns OK response, but no data

**Code to Reproduce**
r = c.get_option_chain('AAPL')
print(r)

**Expected Behavior**
<Response [200 OK]> but with data

**Actual Behavior**
<Response [200 OK]> only getting this

**Error/Exception Log, If Applicable**
When running the debugger I get the following:

![Capture](https://user-images.githubusercontent.com/37028609/125539767-2e2198c8-f724-4279-9b18-f860744a8979.PNG)

**Comment by alexgolec** [comment]
Issues are not an appropriate venue for support. Please visit our discord to ask the community for help:

https://discord.gg/nfrd9gh

**Comment by chartwizard** [comment]
Thanks... and sorry, but I thought this was an issue since I was able to
receive data for the same request using TDA's website.  I will check out
the discord site.

Thanks again,
Mark
