### ISSUE TITLE
Advanced Auth Method for Serverless 

### ISSUE THREAD

**Issue by KJJorgensen** [alexgolec/tda-api#262]
I'm having a problem with the token path not being found when deploying to the cloud with both chalice and flask. The token path is not an issue when I run the app locally. I think the fix lies in the advanced functionality section of the client authorization. There it lists 'tda.auth.client_from_access_functions(api_key, token_read_func, token_write_func, asyncio=False'
as being used in a serverless application. Could this be my problem? My feature request is adding a script to this repository that shows how to make this authentification method work. Maybe just as a template to replace the other Auth methods for those of us struggling to get this app working in the cloud.

Thank you for your time and all the awesome information

**Comment by alexgolec** [comment]
Issues are not an appropriate venue for support. Please visit our discord to ask the community for help:

https://discord.gg/nfrd9gh

**Comment by KJJorgensen** [comment]
This is a feature request... the issue tab allows for feature requests to be submitted.
