### ISSUE TITLE
Continued use of a tda.client.Client

### ISSUE THREAD

**Issue by nicmcd** [alexgolec/tda-api#27]
Given that the access token last for only 30 minutes, what is the behavior of tda-api when reusing the same tda.client.Client for longer than 30 minutes? Will it fail or will it automatically refresh the token?

If it currently fails, how do you feel about adding an auto-refresh to the APIs such that the refresh token is used to retrieve a new access token? If you don't like that idea, what do you suggest? Should the user just timeout the client after 30 minutes and reestablish it?

**Comment by alexgolec** [comment]
It supports transparent token refreshes. See the documentation for more info:

https://tda-api.readthedocs.io/en/latest/auth.html#fetching-a-token-and-creating-a-client
