### ISSUE TITLE
Field Names Inconsistent Across the Board

### ISSUE THREAD

**Issue by J-B-Blankenship** [alexgolec/tda-api#283]
**Is your feature request related to a problem? Please describe.**
tda-api should either default to TDAmeritrade's original field names or standardize across the board (vs. creating our own only for some). This matters for a few reasons. 

1. Standardized approach reduces confusion
2. Current conversion does not match docs [documentation: SYMBOL -> actual: key]
3. Expectation of original field names (ie. similar to historical data http request) has been established
4. Fixing TDAmeritrade's mess of field names saves effort on the end-user of the library

**Describe the solution you'd like**
Pretty straightforward. Either standardize the fields or leave them as is. I can go through to make the field names match the historical data http request because the two schemas are practically the same data (some extra fields with the live data). TDAmeritrade is inconsistent as well on its field names, which is pretty crappy of them considering it's an established company. Standardized names across all data types by this library would make the users' lives easier.

**Describe alternatives you've considered**
Each project holds the responsibility of converting to its own desired field names. While this can be the solution and should be the solution, an effort to standardize the approach of converting/not converting field names should be made.

**Additional context**

**Comment by alexgolec** [comment]
Closing due to vagueness
