### ISSUE TITLE
Complex Option Question

### ISSUE THREAD

**Issue by chotaGit** [alexgolec/tda-api#284]
Hello, 

Thanks for the excellent api. I have a question regarding the usage. Here is my requirement:

TSLA is currently trading at 1008. I would like to buy TSLA 010122 C1000 when TSLA hits 980. Once this is triggered, I would like to place a $3 Trailing stop on the option. This combo uses the underlying stock price to trigger the option buy. 

Thanks in anticipation!

**Comment by alexgolec** [comment]
Issues are not an appropriate venue for support. In the future, please visit our discord to ask the community for help:

https://discord.gg/nfrd9gh
