### ISSUE TITLE
class StrikeRange(Enum) may be inaccurate.

### ISSUE THREAD

**Issue by PeaceLaced** [alexgolec/tda-api#290]
**Description of Bug**
Discussion indicating possible enum bug starts here:
https://discord.com/channels/720378361880248621/720384659732693093/931949628402835456

filter by param `strike_range=` for method `get_option_chain()` using `class StrikeRange(Enum)` does not work as intended

**Code to Reproduce**
code comes from LimitDn on discord.
```
r4 = c.get_option_chain('DASH',
                        contract_type=c.Options.ContractType.CALL,
                        strike_range=c.Options.StrikeRange.OUT_OF_THE_MONEY,
                        from_date=datetime.date(2022,1,15),
                        to_date=datetime.date(2022,1,21))
print(json.dumps(r4.json(), indent=2))
```

**Expected Behavior**
It is expected that enforce enums is a feature, and modifying the lib or bypassing the enum is an exception.

**Actual Behavior**
As per LimitDn on discord, filter by param `strike_range=` for method `get_option_chain()` using `class StrikeRange(Enum)` does not work as intended. He had to modify the StrikeRange class and set the enums to the values indicated on https://developer.tdameritrade.com/option-chains/apis/get/marketdata/chains. Later we found that calling `self.client.set_enforce_enums(False)` and passing the filter manually was a workaround.

**Comment by chartwizard** [comment]
The mapping for StrikeRange is out of sync with the current TD Ameritrade API.  The following code can be used until the code base is updated.
```
# Quick fix, as the TDA values have changed
from tda import client
from enum import Enum

class NewStrikeRange(Enum):
    IN_THE_MONEY = 'ITM'
    NEAR_THE_MONEY = 'NTM'
    OUT_OF_THE_MONEY = 'OTM'
    STRIKES_ABOVE_MARKET = 'SAK'
    STRIKES_BELOW_MARKET = 'SBK'
    STRIKES_NEAR_MARKET = 'SNK'
    ALL = 'ALL' 

client.Client.Options.StrikeRange = NewStrikeRange
client.AsyncClient.Options.StrikeRange = NewStrikeRange
```
