### ISSUE TITLE
get_price_history interval functions should include parameter need_extended_hours_data

### ISSUE THREAD

**Issue by kolyarice** [alexgolec/tda-api#292]
Currently there is a difference in the parameters accepted by the base get_price_history() and the shortcut functions get_price_history_every_* as defined in /tda/client/base.py

The parameter need_extended_hours_data is not included in the spec for the shortcut functions. 

It should be included as it will result in cleaner code in implementations that use this module.

It should be easy to add as the shortcut functions already call the base function.

**Comment by jianlao8** [comment]
Hello,
     I am new to starting to use tda-api and have difficulty using the shortcut functions get_price_history_every_*(). Can someone give me an example to retrieve 5 days of data?

Thank you!

**Comment by kolyarice** [comment]
> Hello, I am new to starting to use tda-api and have difficulty using the shortcut functions get_price_history_every_*(). Can someone give me an example to retrieve 5 days of data?

suggest joining the discord server, and searching the history in the #tda-api-support channel. There's a fair amount of sample code there

This issue can be closed as it is fixed now (Thanks Ashwin & Alex)
