### ISSUE TITLE
Regarding alternative login flow

### ISSUE THREAD

**Issue by AlphaNumeric99** [alexgolec/tda-api#295]
Can there be a way to get the necessary authentication data from a new window similar to how google sign in works on websites?

My use case is I am on Flask hosted on a server and the manual flow is well...too manual so considering there is a redirect URL anyway, can there be a way to redirect to my server and get the data from there on the new window that we opened.

**Comment by alexgolec** [comment]
This feels like something that's the best discussed in the server: https://discord.gg/BEr6y6Xqyv
