### ISSUE TITLE
get_option_chain fails when exp_month param is provided

### ISSUE THREAD

**Issue by nick-ramirez** [alexgolec/tda-api#3]
Example failure:
Before:
Traceback (most recent call last):
  File "C:\my\path\main.py", line 25, in <module>
    assert r.ok, r.raise_for_status()
  File "C:\Python38\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.tdameritrade.com/v1/marketdata/chains?....stuffhere....&expMonth=ExpirationMonth.MAY

The fix is to add exp_month = self.convert_enum(exp_month, self.Options.ExpirationMonth) to line 615 of Client.py

**Comment by alexgolec** [comment]
Interesting. Can you provide some sample code I can use to reproduce?

**Comment by nick-ramirez** [comment]
In your example from reddit, replace the get_price_history call with this:

r = c.get_option_chain('MSFT',
    contract_type = client.Client.Options.ContractType.CALL,
    strike = 180,
    strategy = client.Client.Options.Strategy.SINGLE,
    interval = 5,
    strike_range = client.Client.Options.StrikeRange.IN_THE_MONEY,
    exp_month = client.Client.Options.ExpirationMonth.MAY)

**Comment by alexgolec** [comment]
Just uploaded to pypi, try updating your version and let me know if it solved your issue.

**Comment by nick-ramirez** [comment]
Yeah, this resolves it. Closing the issue.
