### ISSUE TITLE
Is two factor authentication supported?

### ISSUE THREAD

**Issue by ShabaniAmir** [alexgolec/tda-api#30]
Previously when I used the TD Ameritrade API login portal, it wouldn't redirect to the callback url without first entering the code it texted to my phone. I see you use selenium to handle the authentication portal, is it capable of dealing with the 2FA? Does it not required 2FA or does it ask for the code in console?

**Comment by alexgolec** [comment]
Selenium is used to open the API login portal, which asks you for a 2FA. `tda-api` never sees your credentials.
