### ISSUE TITLE
Add async versions of HTTP library calls

### ISSUE THREAD

**Issue by alexgolec** [alexgolec/tda-api#31]
This should save people the trouble of wrapping calls in async functions. 

Notes for myself:
 * Connection pool is probably necessary, although token refreshes are a concern
 * https://docs.authlib.org/en/latest/client/oauth2.html
 * https://docs.authlib.org/en/latest/client/httpx.html

**Comment by ericcgu** [comment]
This shows a good side by side comparison. https://www.terriblecode.com/blog/asynchronous-http-requests-in-python/

**Comment by h00shi** [comment]
> This shows a good side by side comparison. https://www.terriblecode.com/blog/asynchronous-http-requests-in-python/

I usually do this directly with threads.

**Comment by alexgolec** [comment]
You're welcome to do that here as well, although note that token refreshing and connection pooling may be a challenge. If you end up trying it, let me know how it went.

**Comment by nicmcd** [comment]
@alexgolec is there documentation about exactly how and when the token refresh is done? I'd really like to have the ability to have multiple threads performing APIs for me. I'm happy to work on a solution.

**Comment by berzoidberg** [comment]
After toying with authlib and getting it to succumb to my whims, I've added very easy-to-use asyncio support in tda-api. Waiting for authlib to take my changes upstream before we merge this in -- they were missing two key things: a) safe token refreshing in asyncio mode, and b) a matching synchronous API to simplify maintenance. I have PRs submitted for both issues.
