### ISSUE TITLE
Functions expecting arrays should tolerate single scalar values

### ISSUE THREAD

**Issue by alexgolec** [alexgolec/tda-api#33]
Provided they are of the right type.

**Comment by nicmcd** [comment]
I think assuming lists (or any iterable collection) is fine, but just add a check on the type. The example in #32 talks about the "symbols" parameter which is a plural name so the user should expect to give a variable that represents potentially multiple items. It think symbols=["GOOG"] is more readable than symbols="GOOG". 

Just my 2 cents.
