### ISSUE TITLE
get_order() -> when does "Expired" happen?

### ISSUE THREAD

**Issue by nicmcd** [alexgolec/tda-api#34]
Does anyone know when an "Expired" order status happens? I submitted a regular limit-based equity buy order with the duration set to "DAY". The price never dropped enough for the trade to happen. I was waiting for the order to which its status to "Expired" after 4pm ET, but it didn't. Does anyone know if/when it will happen? Am I reading the documentation wrong?

https://www.tdameritrade.com/retail-en_us/resources/pdf/SDPS819.pdf (page 7)

**Comment by alexgolec** [comment]
I recommend taking this question to the discord: https://discord.gg/nfrd9gh

Issues are for bugs in tda-api.
