### ISSUE TITLE
ModuleNotFoundError: No module named 'tda'

### ISSUE THREAD

**Issue by Marcioshub** [alexgolec/tda-api#35]
## Please read the [bug submission guidelines](https://tda-api.readthedocs.io/en/latest/help.html) before submitting a bug.

Not following guidelines may result in your bug being ignored and/or closed. 

*Description of Bug*
Gives a ModuleNotFoundError: No module named 'tda' when trying to use the demo code "here's how you can authenticate and fetch daily historical price data for the past twenty years"

*Code to Reproduce*
from tda import auth, client

*Expected Behavior*
show  historical price data for the past twenty years

*Actual Behavior*
Error: ModuleNotFoundError: No module named 'tda'

**Comment by nicmcd** [comment]
Have you tried using an interactive python interpreter?

```
nic@quasar:~$ python3
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tda
>>> dir(tda)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'auth', 'client', 'orders', 'streaming', 'utils', 'version']
>>> 
```

**Comment by alexgolec** [comment]
Have you followed the instructions outline here to install and set up the package?

https://tda-api.readthedocs.io/en/stable/getting-started.html

**Comment by Marcioshub** [comment]
I figured out the issue, it was my own python3 installs... when i used pip3 it was going to another python3 location (not the one i use). i guess i configured it wrong.
