### ISSUE TITLE
Refresh Token Expires Very Quickly

### ISSUE THREAD

**Issue by githubscum** [alexgolec/tda-api#39]
I've managed to use this library efficiently, however, my refresh token I use has issues expiring after about 4 hours of use. Is there anyway to extend the time to expire? I have used other api libraries for tda and the token lasts for at least a couple days.

**Comment by alexgolec** [comment]
This is an interesting issue, and I'd love to look into it, but I'm afraid I have to close it due to insufficient information. Please re-submit your issue using the bug report template.

**Comment by alexgolec** [comment]
Alternately, you can get help by visiting our discord server: https://discord.gg/M3vjtHj
