### ISSUE TITLE
Make OAuth Token refresh longer

### ISSUE THREAD

**Issue by githubscum** [alexgolec/tda-api#40]
**Is your feature request related to a problem? Please describe.**
OAuth Token Expires too quickly. Only lasts for a couple hours

**Describe the solution you'd like**
I'd like the token to last at least a couple of days or weeks. Maybe specifying what interval would be a good feature

**Describe alternatives you've considered**
I've tried other api's that connect to td ameritrade and I haven't had this same issue with the lifespan of the refresh token itself so it must be how it's created within the tda-api code.

**Additional context**
I really enjoy this library and it's simple to use. However I need the token refresh to last a minimum of 8 hours to use it. I'm stuck refreshing the token for my trading bot every couple of hours. This could lead to devastating errors.

**Comment by alexgolec** [comment]
Can you share some code that reproduces the problem?

**Comment by githubscum** [comment]
Here's the code I use to create the token....

api_key = 'MYTOKEN123@AMER.OAUTHAP'
redirect_url = 'https://localhost'
token_path_new = 'C:\\tdabotnew\\Credentials\\token'


def make_webdriver():
    # Import selenium here because it's slow to import
    from selenium import webdriver

    driver = webdriver.Chrome()
    atexit.register(lambda: driver.quit())
    return driver

tda.auth.client_from_login_flow(make_webdriver(), api_key, redirect_url, token_path_new, redirect_wait_time_seconds=0.1)

I then run this code for example to get the price history....

def get_price_history(symbol, my_login):
    resp = my_login.get_price_history(symbol,
            period_type=Client.PriceHistory.PeriodType.DAY,
            period=Client.PriceHistory.Period.ONE_DAY,
            frequency_type=Client.PriceHistory.FrequencyType.MINUTE,
            frequency=Client.PriceHistory.Frequency.EVERY_MINUTE,
            end_datetime=now_time,
            need_extended_hours_data=True)

    assert resp.ok

    price_history = resp.json()

    price_history = json.dumps(price_history)
    price_history = pd.read_json(price_history)
    price_history = json_normalize(price_history['candles'])
    price_history['datetimestamp'] = pd.to_datetime(price_history['datetime'], unit='ms')
	
    return price_history


I receive this error when the token expires...

Traceback (most recent call last):
  File "mainprice.py", line 34, in <module>
    price_history = main_prices.get_price_history(symbol, my_login)
  File "C:\tdabotnew\main_prices.py", line 17, in get_price_history
    need_extended_hours_data=True)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tda\client.py", line 829, in get_price_history
    return self.__get_request(path, params)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tda\client.py", line 108, in __get_request
    resp = self.session.get(dest, params=params)
  File "C:\ProgramData\Miniconda3\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\requests_oauthlib\oauth2_session.py", line 497, in request
    self.auto_refresh_url, auth=auth, **kwargs
  File "C:\ProgramData\Miniconda3\lib\site-packages\requests_oauthlib\oauth2_session.py", line 446, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "C:\ProgramData\Miniconda3\lib\site-packages\oauthlib\oauth2\rfc6749\clients\base.py", line 421, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "C:\ProgramData\Miniconda3\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 431, in parse_token_response
    validate_token_parameters(params)
  File "C:\ProgramData\Miniconda3\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 438, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "C:\ProgramData\Miniconda3\lib\site-packages\oauthlib\oauth2\rfc6749\errors.py", line 405, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidGrantError: (invalid_grant)

**Comment by githubscum** [comment]
@alexgolec Do you think it's because I wasn't using token.pickle file ext.?
File without ".pickle"
![image](https://user-images.githubusercontent.com/65476409/85925461-31ca4e80-b85e-11ea-9518-b103839326df.png)

file with ".pickle"
![image](https://user-images.githubusercontent.com/65476409/85925480-4ad2ff80-b85e-11ea-8930-b4fff780f2d6.png)

**Comment by alexgolec** [comment]
Very interesting... you’re not the first one to tell me the “.pickle” extension helped. I’ll look into this and update documentation if necessary.

**Comment by githubscum** [comment]
I'm running a sample code throughout the day today. If it makes it through the evening I'll let you know. Also, love the updates you made to the orderbuilder. Keep up the lords work!

**Comment by githubscum** [comment]
@alexgolec changing the extension to .pickle did not resolve the issue unfortunately

**Comment by alexgolec** [comment]
I'm struggling to reproduce your issue, and this is the only issue I've received on this topic, so I'm going to close this ticket. If I get more information I'll update it as needed.
