### ISSUE TITLE
Placing an order with Client.place_order() causes TypeError

### ISSUE THREAD

**Issue by ipdinc** [alexgolec/tda-api#48]
**Description of Bug**

When trying to place an order using `Client.place_order()`, my script throws the error
_TypeError: Object of type 'OrderBuilder' is not JSON serializable_

**Code to Reproduce**

```
import tda
from tda.orders.equities import equity_buy_limit, equity_sell_limit, equity_sell_market
from tda.orders.common import Duration, Session, SpecialInstruction
import json
import logging

tda.debug.enable_bug_report_logging()
logging.getLogger('').addHandler(logging.StreamHandler())

primary_account_id = {REDACTED}
sourceFilePath = 'C:/Anaconda3/envs/tda-api/Scripts/'

# Source code to authenticate client, returns client as object named 'c'
exec(open(sourceFilePath + 'authenticate_tda_client_ipd.py').read())

# Specify order parameters
orderSymbol = 'QQQ'
numberOfShares = 1
limitPrice = 220.0

# Build order object
buyOrder = equity_buy_limit(symbol = orderSymbol,
                            quantity = numberOfShares,
                            price = limitPrice)
buyOrder.set_special_instruction(special_instruction = SpecialInstruction.ALL_OR_NONE)
buyOrder.set_session(session = Session.NORMAL)
buyOrder.set_duration(duration = Duration.DAY)

# Place order
orderResponse = c.place_order(account_id = primary_account_id, order_spec = buyOrder) 
assert orderResponse.ok, raise_for_status()

```

**Expected Behavior**
Order request was expected to complete normally.

**Actual Behavior**
Script throws a TypeError

**Error/Exception Log, If Applicable**
Returning client loaded from token file 'C:/Anaconda3/envs/tda-api/tmp/token_ipd.pickle'
Traceback (most recent call last):
  File "C:/Anaconda3/envs/tda-api/Scripts/test2_ipd.py", line 64, in <module>
    orderResponse = c.place_order(account_id = primary_account_id, order_spec = buyOrder)
  File "C:\Anaconda3\envs\tda-api\lib\site-packages\tda\client.py", line 311, in place_order
    return self.__post_request(path, order_spec)
  File "C:\Anaconda3\envs\tda-api\lib\site-packages\tda\client.py", line 118, in __post_request
    req_num, dest, json.dumps(data, indent=4)))
  File "C:\Anaconda3\envs\tda-api\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Anaconda3\envs\tda-api\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "C:\Anaconda3\envs\tda-api\lib\json\encoder.py", line 437, in _iterencode
    o = _default(o)
  File "C:\Anaconda3\envs\tda-api\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'OrderBuilder' is not JSON serializable

 ### BEGIN REDACTED LOGS ###

[debug.py:150:_enable_bug_report_logging] tda-api version 0.5.0
[auth.py:166:easy_client] Returning client loaded from token file 'C:/Anaconda3/envs/tda-api/tmp/token_ipd.pickle'

**Comment by alexgolec** [comment]
So this is what happens when you forget to call `.build()`on your order builder. This is currently working as intended, but I'll leave this open to fix it because I figure it's easy to autodetect this and build the order for the user.

**Comment by ipdinc** [comment]
Ugh.  I missed that bit in your example on the order templates documentation page.

Thank you so much.
