### ISSUE TITLE
using tda-api on heroku

### ISSUE THREAD

**Issue by spitzbubchen** [alexgolec/tda-api#61]
I tend to run my algorithms on heroku where I deploy by doing a git pull. I am not sure how to run tda-api on heroku as the authentication workflow requires interaction with a web browser. If it is possible to run tda-api on heroku can you offer some guidance on this?

**Comment by alexgolec** [comment]
Issues are not an appropriate venue for support requests. Feel free to ask on our discord: https://discord.gg/nfrd9gh

**Comment by spitzbubchen** [comment]
Okay, will post there.
