### ISSUE TITLE
Getting some different quote info vs the developer websites quote info

### ISSUE THREAD

**Issue by dgnsrekt** [alexgolec/tda-api#63]
## Please read the [bug submission guidelines](https://tda-api.readthedocs.io/en/latest/help.html) before submitting a bug.

Not following guidelines may result in your bug being ignored and/or closed. 

**Description of Bug**
There appears to be an issue with some of the quote data from this api. When comparing the output of the WMT quote from this api vs the output on the TDameritrades developers page there seem to be a few fields that aren't aligned.

**Code to Reproduce**
This is the function I wrote.

    def get_quote_data(self, symbols: List[str]):
        validate_arg_type(symbols, list)
        assert len(symbols) > 0
        assert len(symbols) <= 500, "Max symbols lenght is 500"

        logger.debug(f"getting quote_data for {len(symbols)}")
        try:
            tda_client = self.get_client()
            response = tda_client.get_quotes(symbols=symbols)
            assert response.ok
            return unpack_quote_prices(response)
        except Exception as e:
            logger.error(e)
            raise e
        finally:
            time.sleep(1)

IMPORTANT: Remember to anonymize your code. Be sure to replace API keys/Client IDs with placeholders. Also, never, ever share the contents of your token file. 

**Expected Behavior**
This is the output from https://developer.tdameritrade.com/quotes/apis/get/marketdata/quotes
{
  "WMT": {
    "assetType": "EQUITY",
    "assetMainType": "EQUITY",
    "cusip": "931142103",
    "symbol": "WMT",
    "description": "Walmart Inc. Common Stock",
    "bidPrice": 132.61,
    "bidSize": 200,
    "bidId": "P",
    "askPrice": 132.8,
    "askSize": 100,
    "askId": "P",
    "lastPrice": 132.33,
    "lastSize": 0,
    "lastId": "N",
    "openPrice": 131.56,
    "highPrice": 133.99,
    "lowPrice": 131.45,
    "bidTick": " ",
    "closePrice": 131.47,
    "netChange": 0.86,
    "totalVolume": 7240401,
    "quoteTimeInLong": 1595376000023,
    "tradeTimeInLong": 1595375994977,
    "mark": 132.61,
    "exchange": "n",
    "exchangeName": "NYSE",
    "marginable": true,
    "shortable": true,
    "volatility": 0.0204,
    "digits": 2,
    "52WkHigh": 134.13,
    "52WkLow": 102,
    "nAV": 0,
    "peRatio": 25.0554,
    "divAmount": 2.16,
    "divYield": 1.64,
    "divDate": "2020-08-13 00:00:00.000",
    "securityStatus": "Normal",
    "regularMarketLastPrice": 132.33,
    "regularMarketLastSize": 3770,
    "regularMarketNetChange": 0.86,
    "regularMarketTradeTimeInLong": 1595372400000,
    "netPercentChangeInDouble": 0.6541,
    "markChangeInDouble": 1.14,
    "markPercentChangeInDouble": 0.8671,
    "regularMarketPercentChangeInDouble": 0.6541,
    "delayed": true
  }
}

**Actual Behavior**
This is the output from this api. 
{
'assetType': 'EQUITY',
'assetMainType': 'EQUITY',
'cusip': '931142103',
'symbol': 'WMT',
'description': 'Walmart Inc. Common Stock',
'bidPrice': 132.61,
'bidSize': 200,
'bidId': 'P',
'askPrice': 132.8,
'askSize': 100,
'askId': 'P',
'lastPrice': 132.61,         <- issue
'lastSize': 0,
'lastId': 'P',                      <-issue
'openPrice': 131.56,
'highPrice': 133.99,
'lowPrice': 131.45,
'bidTick': ' ',
'closePrice': 131.47,
'netChange': 1.14,       <-issue
'totalVolume': 7240401,
'quoteTimeInLong': 1595376000023,
'tradeTimeInLong': 1595375994977,
'mark': 132.61,
'exchange': 'n',
'exchangeName': 'NYSE',
'marginable': True,
'shortable': True,
'volatility': 0.0202,
'digits': 2,
'52WkHigh': 134.13,
'52WkLow': 102.0,
'nAV': 0.0,
'peRatio': 25.0554,
'divAmount': 2.16,
'divYield': 1.64,
'divDate': '2020-08-13 00:00:00.000',
'securityStatus': 'Normal',
'regularMarketLastPrice': 132.33,
'regularMarketLastSize': 3770,
'regularMarketNetChange': 0.86,
'regularMarketTradeTimeInLong': 1595372400000,
'netPercentChangeInDouble': 0.8671,                  <-issue
'markChangeInDouble': 1.14,
'markPercentChangeInDouble': 0.8671,
'regularMarketPercentChangeInDouble': 0.6541,
'delayed': False}

**Error/Exception Log, If Applicable**
See here to learn how to turn on debug logging: https://tda-api.readthedocs.io/en/latest/help.html

**Comment by dgnsrekt** [comment]
Additional information. I'm using version 0.6.1.
poetry.lock file
```
[[package]]
category = "main"
description = "An unofficial wrapper around the TD Ameritrade HTTP API."
name = "tda-api"
optional = false
python-versions = ">=3.6"
version = "0.6.1"

```

**Comment by alexgolec** [comment]
How much time passed between you performing these calls? 

Also, please double check that you've signed exchange agreements to enable realtime streaming. You can check this by calling this endpoint: 

https://tda-api.readthedocs.io/en/latest/client.html#tda.client.Client.get_user_principals

And looking for the bit that looks like this: 

```
  "quotes": {
    "isNyseDelayed": false,
    "isNasdaqDelayed": false,
    "isOpraDelayed": false,
    "isAmexDelayed": false,
    "isCmeDelayed": false,
    "isIceDelayed": false,
    "isForexDelayed": false
  },
```

**Comment by dgnsrekt** [comment]
So, I took both quotes samples about a minute apart while the market is closed. I probably requested both samples about 10 minutes before I posted the issue.

Also, here is the output from get_user_principals.
```
"quotes" : {
"isNyseDelayed" : false,
"isNasdaqDelayed" : false,
"isOpraDelayed" : false,
"isAmexDelayed" : false,
"isCmeDelayed" : true,
"isIceDelayed" : true,
"isForexDelayed" : true
},
```

**Comment by alexgolec** [comment]
What happens if you request samples at as close to the same time as you can?

**Comment by dgnsrekt** [comment]
![tda_lastPrice](https://user-images.githubusercontent.com/25717871/88129997-0b6aab00-cb9f-11ea-9ae0-c9d4430bc4e0.gif)

**Comment by alexgolec** [comment]
Very interesting... Care to bring this to our discord? We can have a longer discussion there: 

https://discord.gg/nfrd9gh
