### ISSUE TITLE
Floating Point Errors

### ISSUE THREAD

**Issue by ddouglas87** [alexgolec/tda-api#67]
**Description of Bug**
On the timesale stream I've noticed quite a few floating point errors.

**Code to Reproduce**
```
    await stream_client.timesale_futures_subs(['/GC'])
    stream_client.add_timesale_futures_handler(
        lambda msg: print(msg)
    )
```

**Output**

> {'service': 'TIMESALE_FUTURES', 'timestamp': 1595903805310, 'command': 'SUBS', 'content': [{'seq': 0, 'key': '/GCZ20', 'TRADE_TIME': 1595903802318, 'LAST_PRICE': 1993.3000000000002, 'LAST_SIZE': 1.0, 'LAST_SEQUENCE': 14257234}]}
> {'service': 'TIMESALE_FUTURES', 'timestamp': 1595903807125, 'command': 'SUBS', 'content': [{'seq': 1, 'key': '/GCZ20', 'TRADE_TIME': 1595903807076, 'LAST_PRICE': 1993.5, 'LAST_SIZE': 1.0, 'LAST_SEQUENCE': 14257235}]}
> {'service': 'TIMESALE_FUTURES', 'timestamp': 1595903814876, 'command': 'SUBS', 'content': [{'seq': 2, 'key': '/GCZ20', 'TRADE_TIME': 1595903814848, 'LAST_PRICE': 1993.2, 'LAST_SIZE': 1.0, 'LAST_SEQUENCE': 14257236}]}
> {'service': 'TIMESALE_FUTURES', 'timestamp': 1595903823272, 'command': 'SUBS', 'content': [{'seq': 3, 'key': '/GCZ20', 'TRADE_TIME': 1595903823201, 'LAST_PRICE': 1993.1000000000001, 'LAST_SIZE': 1.0, 'LAST_SEQUENCE': 14257237}]}

**Expected Behavior vs Actual Behavior**

LAST_PRICE is often off, eg `1993.1000000000001`.  The minimum tick of /GC is 10¢ so it should never be more than one digit past the decimal place.  The correct price is `1993.1`.

LAST_SIZE is showing a floating point number too, eg `1.0`.  As far as I know TDA does not do fractional shares.  The correct size is `1`.

It appears like this api is converting the incoming string from TDA to a double.  One solution, and possibly the ideal solution is to keep all numbers as strings.  Python's decimal type has been known to automatically convert numbers into a double, so it's ideal to keep all numbers as a string.

**Comment by alexgolec** [comment]
Unfortunately, this simply appears to be the way TDAmeritrade's API works. `tda-api` does not perform any conversion of the received stream data, it simply parses the received JSON object and relabels certain difficult-to-interpret keys to human-readable values. 

You can verify this by enabling debug printing and inspecting the raw, unprocessed data that is received from the API: 

https://tda-api.readthedocs.io/en/stable/help.html#gather-logs-for-your-bug-report

**Comment by alexgolec** [comment]
Side note: interestingly enough, TDA actually does actually support fractional shares as part of the dividend reinvestment program, which will spend the entirety of your dividends on fractional shares. Whether this was a factor in their decision to return share counts as floating point values is unclear.

**Comment by ddouglas87** [comment]
What a garbage api.  (Not this, TDA itself.)

Thank you!

**Comment by alexgolec** [comment]
¯\_(ツ)_/¯
