### ISSUE TITLE
Idiot Proof Oauth

### ISSUE THREAD

**Issue by sargun** [alexgolec/tda-api#70]
**Is your feature request related to a problem? Please describe.**
Using the Selenium based driver makes me uncomfortable, and it's brittle-ish.

**Describe the solution you'd like**
I can think of a couple different solutions:
1. We run a flask app on https://127.0.0.1:5050 (or some such), and we ask the user to set their oauth callback URL to https://127.0.0.1:5050/oauth
2. We have an actual developer "app" that has a hosted little lambda function and let's people "sign up". [This is scary, since it would mean someone in the project would have to run a TDA Developer App]
3. We do #1, but with an ngrok URL and letsencrypt
4. We do something between 1 and 2, of having a site like http://tda-api-helper.com, which people can set as their oauth callback URLs, and the site can have a way to retrieve your URLs.

Generally, the idea is, what if we used something like a Flask App to do auth, rather than the webdriver thing? 

**Additional context**
I'm more than willing to help implement 1, 3, and 4. If the project is willing to add it. Let me know what the preference is.

**Comment by alexgolec** [comment]
I'm not sure I understand. There doesn't actually need to be a server running at the callback URL, the library just waits for the browser to attempt to contact the callback URL and polls for the change in address. The query parameters to the callback URL contain all information needed to log in. 

Let's take this to our discord? I feel like there's some discussion that has to happen before we continue on this feature request: 

discord.gg/nfrd9gh

**Comment by sargun** [comment]
I commented about it here: https://discordapp.com/channels/720378361880248621/720378361880248624/739622823462567998

**Comment by sargun** [comment]
We talked about this offline, and the best way seemed to be that you could construct your own 

requests_oauthlib.OAuth2Session, and use it for instantiating tda.client.Client(Client)
