### ISSUE TITLE
client.place_order() error while executing

### ISSUE THREAD

**Issue by mikelhsia** [alexgolec/tda-api#84]
## Please read the [bug submission guidelines](https://tda-api.readthedocs.io/en/latest/help.html) before submitting a bug.

Not following guidelines may result in your bug being ignored and/or closed. 

**Description of Bug**
While I'm following the example in the [Online Doc](https://tda-api.readthedocs.io/en/stable/order-templates.html#using-these-templates) sample code as below, I've encountered the issue saying parameter `order_spec` is missing. 

```python
from tda.orders.equities import equity_buy_limit
from tda.orders.common import Duration, Session

client = ... # See "Authentication and Client Creation"

client.place_order(
    equity_buy_limit('GOOG', 1, 1250.0)
        .set_duration(Duration.GOOD_TILL_CANCEL)
        .set_session(Session.SEAMLESS)
        .build())
```
After looking into the source code, I found that I didn't specify the parameter `account_id` in order to place the order in specific account. 

After I specified the account_id, now I'm seeing this
```python
Traceback (most recent call last):
  File "td_ameritrade_api.py", line 57, in <module>
    .set_session(Session.SEAMLESS)
  File "/usr/local/lib/python3.7/site-packages/tda/client.py", line 315, in place_order
    return self.__post_request(path, order_spec)
  File "/usr/local/lib/python3.7/site-packages/tda/client.py", line 123, in __post_request
    tda.debug.register_redactions_from_response(resp)
  File "/usr/local/lib/python3.7/site-packages/tda/debug.py", line 54, in register_redactions_from_response
    register_redactions(resp.json())
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

However, I do see the order is placed in the TD Ameritrade platform. So I'm assuming the parser part of the JSON response is flaw.

**Code to Reproduce**
```python
response = c.place_order(
    account_id={Account Number of my TD account},
    order_spec=equity_sell_limit('CCL', 1, 18.20)
    .set_duration(Duration.DAY)
    .set_session(Session.SEAMLESS)
    .build()
)
```

IMPORTANT: Remember to anonymize your code. Be sure to replace API keys/Client IDs with placeholders. Also, never, ever share the contents of your token file. 

**Expected Behavior**
Would return the order id as said in the doc

**Actual Behavior**
Saw error `simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Error/Exception Log, If Applicable**
See here to learn how to turn on debug logging: https://tda-api.readthedocs.io/en/latest/help.html
```
[client.py:56:__log_response] Req 1: GET response: 201, content=
```

**Comment by tahmid29** [comment]
@alexgolec  Please update the documentation here in the example to add the accountId: https://tda-api.readthedocs.io/en/stable/order-templates.html

I think users will keep creating issue like this till we fix it in the doc.

**Comment by mikelhsia** [comment]
Hi @alexgolec 
I saw the response just now. Thanks for the feedback. 

To answer your question, I'm running the script on my local laptop with anaconda env. Also, I'm using python 3.7 with a built-in JSON library. 

Do let me know if you want more details so that I can share them with you.
