### ISSUE TITLE
Operation on a headless server

### ISSUE THREAD

**Issue by nicmcd** [alexgolec/tda-api#9]
Is it possible to get the authentication flow to work on a headless server? I've got the authentication flow to work on a regular machine, then tried to copy the token file to a different machine, but it still attempts to open the chromedriver to authenticate again. Thoughts?

**Comment by ofertal** [comment]
Maybe this can help:

payload = {'grant_type': 'refresh_token',
"client_id":"<fill>",
"redirect_uri":"<fill>",
"refresh_token":"<fill>"}

res=requests.post('https://api.tdameritrade.com/v1/oauth2/token',
headers={'Content-Type': 'application/x-www-form-urlencoded'},
data={'grant_type': payload['grant_type'],
'refresh_token': payload["refresh_token"],
'client_id': payload["client_id"]})

payload.update(res.json())

token_path = 'token.pickle'
import pickle
with open(token_path, 'wb') as f:
	pickle.dump(payload, f)

**Comment by alexgolec** [comment]
Hey, I'm happy to look into this but I can't offer you any help unless you share code that I can use to reproduce your issue.

**Comment by nicmcd** [comment]
Alex, I'm using your example code:

```
try:
  c = tda.auth.client_from_token_file(token_path, api_key)
except FileNotFoundError:
  from selenium import webdriver
  with webdriver.Chrome() as driver:
    c = tda.auth.client_from_login_flow(
      driver, api_key, redirect_uri, token_path)
```

I understand that the per 90 day login needs to be done on a machine with a GUI so that the webdriver can open the web page and perform the log in. What I'm trying to do is run my application on a headless server for which I can not open chrome. 

It turns out I had a sequence of events problem. I'm now able to run my app on the headless server. Presumably I just need to reauthorize using a regular machine once every 90 days.
