### ISSUE TITLE
<Response [400]>

### ISSUE THREAD

**Issue by Eyalarasan** [alexgolec/tda-api#91]
Hi,

I'm able place single order, but when I try Trigger/OCO order getting the <Response [400]>
Please help me fix this issue.
Thanks,
Eyal

PS: Here is the script used for trigger/OCO order

myorder2 = {
    "session": "NORMAL",
    "duration": "GOOD_TILL_CANCEL",
    "orderType": "LIMIT",
    "price": "6.52",
    "orderLegCollection": [
        {
            "instruction": "BUY",
            "instrument": {
                "assetType": "EQUITY",
                "symbol": "ET"
            },
            "quantity": 10
        }
    ],
    "orderStrategyType": "TRIGGER",
    "childOrderStrategies": [
        {
            "orderStrategyType": "OCO",
            "childOrderStrategies": [
                {
                    "session": "NORMAL",
                    "duration": "GOOD_TILL_CANCEL",
                    "orderType": "LIMIT",
                    "price": "6.57",
                    "orderLegCollection": [
                        {
                            "instruction": "SELL",
                            "instrument": {
                                "assetType": "EQUITY",
                                "symbol": "ET"
                            },
                            "quantity": 10
                        }
                    ]
                },
                {
                    "session": "NORMAL",
                    "duration": "GOOD_TILL_CANCEL",
                    "orderType": "STOP_LIMIT",
                    "stopPrice": "6.40",
                    "orderLegCollection": [
                        {
                            "instruction": "SELL",
                            "instrument": {
                                "assetType": "EQUITY",
                                "symbol": "ET"
                            },
                            "quantity": 10
                        }
                    ]
                }
            ]
        }
    ]
}

 print (myorer2)
 resp = c.place_order(config.account_id, myorder2)
 resp = c.place_order(account_id=config.account_id,order_spec=myorder2)
 print (resp)

**Comment by alexgolec** [comment]
Issues are not an appropriate venue for help requests. Feel free to join our discord to ask questions:

https://discord.gg/M3vjtHj
