### ISSUE TITLE
Streaming Client Login Error in case of multiple accounts 

### ISSUE THREAD

**Issue by shashiHUB** [alexgolec/tda-api#93]
### Throwing an exception if you have multiple accounts. Some of them are my own and some of them are linked from family members)

- Tried with all the combinations 

1. Access token was successful
2. When I tried with my primary account id, error thrown as mentioned at the bottom
3. Also tried without id and received an  error as "multiple accounts"

 **Error**
_Error:in _init_from_principals
    self._account_id))
ValueError: no account found with account_id xxxxxxxxx_

**While executing the following statement  **
stream_client = StreamClient(client, account_id=xxxxxxx)
async def read_stream():
    await stream_client.login().

**Comment by alexgolec** [comment]
Issues are not an appropriate venue for help requests. Feel free to join our discord to ask questions:

https://discord.gg/M3vjtHj
