### ISSUE TITLE
resp.json() error with Session.NORMAL

### ISSUE THREAD

**Issue by thdoan** [alexgolec/tda-api#95]
## Please read the [bug submission guidelines](https://tda-api.readthedocs.io/en/latest/help.html) before submitting a bug.

Not following guidelines may result in your bug being ignored and/or closed. 

**Description of Bug**
When using `Session.NORMAL`, `print(resp.json())` returns an error. `Session.SEAMLESS` works fine though.

**Code to Reproduce**
```
resp = c.place_order(config.account_id,
    equity_buy_limit('AAPL', 1, 1.00)
        .set_duration(Duration.GOOD_TILL_CANCEL)
        .set_session(Session.NORMAL)
        .build())

print(resp.json())
```

IMPORTANT: Remember to anonymize your code. Be sure to replace API keys/Client IDs with placeholders. Also, never, ever share the contents of your token file. 

**Expected Behavior**
`print(resp.json())` should output JSON.

**Actual Behavior**
`print(resp.json())` returns this error:

```
Traceback (most recent call last):
  File "c:/dev/Git/tda-api/examples/test.py", line 23, in <module>
    print(resp.json())
  File "C:\dev\Miniconda3\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\dev\Miniconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\dev\Miniconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\dev\Miniconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Python version: 3.7.6 64-bit

**Error/Exception Log, If Applicable**
See here to learn how to turn on debug logging: https://tda-api.readthedocs.io/en/latest/help.html

**Comment by alexgolec** [comment]
Very interesting, can you share what the results are with `Session.SEAMLESS`?

**Comment by thdoan** [comment]
@alexgolec my bad, `Session.SEAMLESS` returned the same error. I don't think there was a case where it did not return an error. If it's because the response is not supposed to be in JSON format, then you can close this.

**Comment by alexgolec** [comment]
That's correct, there isn't a JSON response on success. I've made this change to reflect that in the documentation: https://github.com/alexgolec/tda-api/commit/38221b6e292acd8c3aa80e6b8a0f46a3f03f390b
