### ISSUE TITLE
OCO order did not go through.

### ISSUE THREAD

**Issue by thdoan** [alexgolec/tda-api#97]
## Please read the [bug submission guidelines](https://tda-api.readthedocs.io/en/latest/help.html) before submitting a bug.

Not following guidelines may result in your bug being ignored and/or closed. 

**Description of Bug**
When I place an OCO order through ToS manually, it's placed as expected. However, when I place it through tda-api, it's not placed since I see no new transactions in ToS.

**Code to Reproduce**
```
c.place_order(config.account_id,
    one_cancels_other(
        equity_sell_limit('FB', 1, 400.00),
        equity_sell_limit('FB', 1, 200.00)
            .set_order_type(OrderType.STOP_LIMIT)
            .clear_price()
            .set_stop_price(200.01)
    )
)
```

IMPORTANT: Remember to anonymize your code. Be sure to replace API keys/Client IDs with placeholders. Also, never, ever share the contents of your token file. 

**Expected Behavior**
The OCO order is placed and shows up in ToS.

**Actual Behavior**
No errors are thrown in Python, but the order is not placed either. Is there a way to enable more logging so I can provide you with a log?

**Error/Exception Log, If Applicable**
See here to learn how to turn on debug logging: https://tda-api.readthedocs.io/en/latest/help.html

**Comment by alexgolec** [comment]
Issues are not an appropriate venue for help requests. Feel free to join our discord to ask questions:

https://discord.gg/M3vjtHj
