### ISSUE TITLE
birthday_dividends.py 403 'Forbidden' when pulling S&P 500 tickers from website

### ISSUE THREAD

**Issue by hmanfarmer** [alexgolec/tda-api#98]
**Description of Bug**
Line 32 of [birthday_dividends.py](https://github.com/alexgolec/tda-api/blob/51a97dd0f7be78026caeda62407581c0122ffcfe/examples/birthday_dividends.py)
```python
# Load S&P 500 composition from documentation
sp500 = urlopen(
    'https://tda-api.readthedocs.io/en/latest/_static/sp500.txt').read().decode().split()
```
throws error `HTTP Error 403: Forbidden`.

**Code to Reproduce**
```python
from urllib.request import urlopen

sp500 = urlopen(
    'https://tda-api.readthedocs.io/en/latest/_static/sp500.txt').read().decode().split()
```

**Expected Behavior**
Return a list of S&P 500 stocks, scraped from website.

**Likely Cause**
[HTTP error 403 in Python 3 Web Scraping](https://stackoverflow.com/questions/16627227/http-error-403-in-python-3-web-scraping/31758803)

**Potential Solution**
```python
from urllib.request import Request, urlopen

req = Request('https://tda-api.readthedocs.io/en/latest/_static/sp500.txt', headers={'User-Agent': 'Mozilla/5.0'})
sp500 = urlopen(req).read().decode().split()
```

**Comment by alexgolec** [comment]
@berzoidberg are you sure #99 fixes this?

**Comment by berzoidberg** [comment]
Yup. If you check the commits I change it to use httpx, and add a user-agent header that bypasses the robot restrictions. Tested it, works fine
